class PythonControlStructures:
    def __init__(self):
        pass

    def show_python_operators(self):
        """Shows Python Operators overview - all operator categories"""
        print("\n" + "=" * 75)
        print(">> PYTHON OPERATORS OVERVIEW")
        print("=" * 75)
        print()
        print("Operators perform operations on variables and values.")
        print()
        print("1. OPERATOR CATEGORIES:")
        print("+-------------------------------------------+")
        print("| Type         | Examples                |")
        print("|--------------|-------------------------|")
        print("| Arithmetic   | +, -, *, /, //, %, **   |")
        print("| Assignment   | =, +=, -=, *=, /=       |")
        print("| Comparison   | ==, !=, <, >, <=, >=    |")
        print("| Logical      | and, or, not            |")
        print("| Identity     | is, is not              |")
        print("| Membership   | in, not in              |")
        print("| Bitwise      | &, |, ^, ~, <<, >>      |")
        print("+-------------------------------------------+")
        print()
        print("2. BASIC EXAMPLES:")
        print("+-------------------------------------------+")
        print("| x = 10                                  |")
        print("| y = 3                                   |")
        print("|                                         |")
        print("| print(x + y)    # 13 (addition)        |")
        print("| print(x > y)    # True (comparison)    |")
        print("| print(x and y)  # 3 (logical)          |")
        print("+-------------------------------------------+")

    def show_python_arithmetic(self):
        """Shows Python Arithmetic operators with examples"""
        print("\n" + "=" * 75)
        print(">> ARITHMETIC OPERATORS")
        print("=" * 75)
        print()
        print("Arithmetic operators perform mathematical operations.")
        print()
        print("1. BASIC ARITHMETIC:")
        print("+-------------------------------------------+")
        print("| x = 15                                  |")
        print("| y = 4                                   |")
        print("|                                         |")
        print("| print(x + y)    # 19  Addition         |")
        print("| print(x - y)    # 11  Subtraction      |")
        print("| print(x * y)    # 60  Multiplication   |")
        print("| print(x / y)    # 3.75 Division        |")
        print("+-------------------------------------------+")
        print()
        print("2. ADVANCED ARITHMETIC:")
        print("+-------------------------------------------+")
        print("| print(x // y)   # 3   Floor division   |")
        print("| print(x % y)    # 3   Modulus          |")
        print("| print(x ** y)   # 50625 Exponentiation |")
        print("|                                         |")
        print("| # Negative numbers                      |")
        print("| print(-x)       # -15 Unary minus      |")
        print("| print(+x)       # 15  Unary plus       |")
        print("+-------------------------------------------+")
        print()
        print("3. STRING ARITHMETIC:")
        print("+-------------------------------------------+")
        print("| # String concatenation                  |")
        print("| first = 'Hello'                        |")
        print("| last = 'World'                         |")
        print("| print(first + ' ' + last)  # Hello World |")
        print("|                                         |")
        print("| # String repetition                     |")
        print("| print('Ha' * 3)  # HaHaHa              |")
        print("+-------------------------------------------+")

    def show_python_assignment(self):
        """Shows Python Assignment operators including compound assignment"""
        print("\n" + "=" * 75)
        print(">> ASSIGNMENT OPERATORS")
        print("=" * 75)
        print()
        print("Assignment operators assign values to variables.")
        print()
        print("1. BASIC ASSIGNMENT:")
        print("+-------------------------------------------+")
        print("| x = 5              # Simple assignment |")
        print("| y = x              # Copy value         |")
        print("+-------------------------------------------+")
        print()
        print("2. COMPOUND ASSIGNMENT:")
        print("+-------------------------------------------+")
        print("| x = 10                                  |")
        print("|                                         |")
        print("| x += 3     # Same as x = x + 3  (13)   |")
        print("| x -= 2     # Same as x = x - 2  (11)   |")
        print("| x *= 2     # Same as x = x * 2  (22)   |")
        print("| x /= 4     # Same as x = x / 4  (5.5)  |")
        print("| x //= 2    # Same as x = x // 2 (2.0)  |")
        print("| x %= 3     # Same as x = x % 3  (2.0)  |")
        print("| x **= 3    # Same as x = x ** 3 (8.0)  |")
        print("+-------------------------------------------+")
        print()
        print("3. BITWISE ASSIGNMENT:")
        print("+-------------------------------------------+")
        print("| x = 12     # Binary: 1100               |")
        print("|                                         |")
        print("| x &= 7     # AND: x = x & 7   (4)      |")
        print("| x |= 3     # OR:  x = x | 3   (7)      |")
        print("| x ^= 5     # XOR: x = x ^ 5   (2)      |")
        print("| x >>= 1    # Right shift: x = x >> 1 (1) |")
        print("| x <<= 2    # Left shift: x = x << 2 (4) |")
        print("+-------------------------------------------+")

    def show_python_comparison(self):
        """Shows Python Comparison operators for comparing values"""
        print("\n" + "=" * 75)
        print(">> COMPARISON OPERATORS")
        print("=" * 75)
        print()
        print("Comparison operators compare two values and return True/False.")
        print()
        print("1. BASIC COMPARISONS:")
        print("+-------------------------------------------+")
        print("| x = 5                                   |")
        print("| y = 3                                   |")
        print("|                                         |")
        print("| print(x == y)   # False (equal to)     |")
        print("| print(x != y)   # True  (not equal)    |")
        print("| print(x > y)    # True  (greater than) |")
        print("| print(x < y)    # False (less than)    |")
        print("| print(x >= y)   # True  (greater/equal)|")
        print("| print(x <= y)   # False (less/equal)   |")
        print("+-------------------------------------------+")
        print()
        print("2. STRING COMPARISON:")
        print("+-------------------------------------------+")
        print("| name1 = 'Alice'                         |")
        print("| name2 = 'Bob'                           |")
        print("|                                         |")
        print("| print(name1 == name2)  # False         |")
        print("| print(name1 < name2)   # True (A < B)  |")
        print("+-------------------------------------------+")
        print()
        print("3. CHAINED COMPARISONS:")
        print("+-------------------------------------------+")
        print("| age = 25                                |")
        print("| print(18 <= age <= 65)  # True         |")
        print("|                                         |")
        print("| # Same as: 18 <= age and age <= 65     |")
        print("+-------------------------------------------+")

    def show_python_logical(self):
        """Shows Python Logical operators (and, or, not)"""
        print("\n" + "=" * 75)
        print(">> LOGICAL OPERATORS")
        print("=" * 75)
        print()
        print("Logical operators combine boolean values.")
        print()
        print("1. AND OPERATOR:")
        print("+-------------------------------------------+")
        print("| x = 5                                   |")
        print("| print(x > 0 and x < 10)  # True        |")
        print("| print(x > 10 and x < 20) # False       |")
        print("|                                         |")
        print("| # Returns first falsy or last value    |")
        print("| print(5 and 3)           # 3           |")
        print("| print(0 and 5)           # 0           |")
        print("+-------------------------------------------+")
        print()
        print("2. OR OPERATOR:")
        print("+-------------------------------------------+")
        print("| age = 25                                |")
        print("| print(age < 18 or age > 65)  # False   |")
        print("| print(age < 30 or age > 65)  # True    |")
        print("|                                         |")
        print("| # Returns first truthy or last value   |")
        print("| print(0 or 5)            # 5           |")
        print("| print(3 or 5)            # 3           |")
        print("+-------------------------------------------+")
        print()
        print("3. NOT OPERATOR:")
        print("+-------------------------------------------+")
        print("| is_active = True                        |")
        print("| print(not is_active)     # False       |")
        print("| print(not 0)             # True        |")
        print("| print(not [])            # True        |")
        print("| print(not 'hello')       # False       |")
        print("+-------------------------------------------+")

    def show_python_identity(self):
        """Shows Python Identity operators (is, is not)"""
        print("\n" + "=" * 75)
        print(">> IDENTITY OPERATORS")
        print("=" * 75)
        print()
        print("Identity operators check if objects are the same in memory.")
        print()
        print("1. IS OPERATOR:")
        print("+-------------------------------------------+")
        print("| x = [1, 2, 3]                           |")
        print("| y = [1, 2, 3]                           |")
        print("| z = x                                   |")
        print("|                                         |")
        print("| print(x is y)            # False       |")
        print("| print(x is z)            # True        |")
        print("| print(x == y)            # True        |")
        print("+-------------------------------------------+")
        print()
        print("2. IS NOT OPERATOR:")
        print("+-------------------------------------------+")
        print("| a = None                                |")
        print("| b = 0                                   |")
        print("|                                         |")
        print("| print(a is not None)     # False       |")
        print("| print(b is not None)     # True        |")
        print("+-------------------------------------------+")
        print()
        print("3. COMMON USE CASES:")
        print("+-------------------------------------------+")
        print("| # Check for None                        |")
        print("| value = None                            |")
        print("| if value is None:                       |")
        print("|     print('No value')                   |")
        print("|                                         |")
        print("| # Check boolean values                  |")
        print("| flag = True                             |")
        print("| if flag is True:                        |")
        print("|     print('Flag is set')                |")
        print("+-------------------------------------------+")

    def show_python_membership(self):
        """Shows Python Membership operators (in, not in)"""
        print("\n" + "=" * 75)
        print(">> MEMBERSHIP OPERATORS")
        print("=" * 75)
        print()
        print("Membership operators check if a value exists in a collection.")
        print()
        print("1. IN OPERATOR:")
        print("+-------------------------------------------+")
        print("| # Lists                                 |")
        print("| fruits = ['apple', 'banana', 'cherry']  |")
        print("| print('apple' in fruits)    # True     |")
        print("| print('grape' in fruits)    # False    |")
        print("|                                         |")
        print("| # Strings                               |")
        print("| text = 'Hello World'                   |")
        print("| print('World' in text)      # True     |")
        print("| print('world' in text)      # False    |")
        print("+-------------------------------------------+")
        print()
        print("2. NOT IN OPERATOR:")
        print("+-------------------------------------------+")
        print("| numbers = [1, 2, 3, 4, 5]               |")
        print("| print(6 not in numbers)     # True     |")
        print("| print(3 not in numbers)     # False    |")
        print("|                                         |")
        print("| # Dictionary keys                       |")
        print("| person = {'name': 'Alice', 'age': 30}   |")
        print("| print('name' in person)     # True     |")
        print("| print('email' not in person) # True    |")
        print("+-------------------------------------------+")
        print()
        print("3. PRACTICAL EXAMPLES:")
        print("+-------------------------------------------+")
        print("| # Validation                            |")
        print("| valid_colors = ['red', 'green', 'blue'] |")
        print("| user_color = 'yellow'                   |")
        print("|                                         |")
        print("| if user_color not in valid_colors:      |")
        print("|     print('Invalid color!')            |")
        print("+-------------------------------------------+")

    def show_python_bitwise(self):
        """Shows Python Bitwise operations"""
        print("\n" + "=" * 75)
        print(">> BITWISE OPERATORS")
        print("=" * 75)
        print()
        print("Bitwise operators work on binary representation of numbers.")
        print()
        print("1. BASIC BITWISE OPERATORS:")
        print("+-------------------------------------------+")
        print("| a = 12    # Binary: 1100                |")
        print("| b = 7     # Binary: 0111                |")
        print("|                                         |")
        print("| print(a & b)     # 4  (0100) AND       |")
        print("| print(a | b)     # 15 (1111) OR        |")
        print("| print(a ^ b)     # 11 (1011) XOR       |")
        print("| print(~a)        # -13 NOT (complement)|")
        print("+-------------------------------------------+")
        print()
        print("2. BIT SHIFTING:")
        print("+-------------------------------------------+")
        print("| x = 8     # Binary: 1000                |")
        print("|                                         |")
        print("| print(x << 1)    # 16 (10000) Left     |")
        print("| print(x << 2)    # 32 (100000)         |")
        print("| print(x >> 1)    # 4  (100) Right      |")
        print("| print(x >> 2)    # 2  (10)             |")
        print("+-------------------------------------------+")
        print()
        print("3. PRACTICAL USES:")
        print("+-------------------------------------------+")
        print("| # Fast multiplication/division by 2     |")
        print("| num = 100                               |")
        print("| print(num << 1)      # 200 (×2)        |")
        print("| print(num >> 1)      # 50  (÷2)        |")
        print("|                                         |")
        print("| # Check if number is even               |")
        print("| print((num & 1) == 0) # True (even)    |")
        print("+-------------------------------------------+")

    def show_python_precedence(self):
        """Shows Python Operator precedence rules"""
        print("\n" + "=" * 75)
        print(">> OPERATOR PRECEDENCE")
        print("=" * 75)
        print()
        print("Operator precedence determines evaluation order.")
        print()
        print("PRECEDENCE ORDER (highest to lowest):")
        print("+-------------------------------------------+")
        print("| 1. ()                    Parentheses   |")
        print("| 2. **                    Exponentiation|")
        print("| 3. +x, -x, ~x            Unary         |")
        print("| 4. *, /, //, %           Multiplication |")
        print("| 5. +, -                  Addition      |")
        print("| 6. <<, >>                Bit shifts    |")
        print("| 7. &                     Bitwise AND   |")
        print("| 8. ^                     Bitwise XOR   |")
        print("| 9. |                     Bitwise OR    |")
        print("| 10. ==, !=, <, <=, >, >= Comparisons   |")
        print("| 11. is, is not           Identity      |")
        print("| 12. in, not in           Membership    |")
        print("| 13. not                  Logical NOT   |")
        print("| 14. and                  Logical AND   |")
        print("| 15. or                   Logical OR    |")
        print("+-------------------------------------------+")
        print()
        print("EXAMPLES:")
        print("+-------------------------------------------+")
        print("| # Without parentheses                   |")
        print("| result = 2 + 3 * 4        # 14 not 20  |")
        print("| result = 2 ** 3 ** 2      # 512 not 64 |")
        print("|                                         |")
        print("| # With parentheses for clarity          |")
        print("| result = (2 + 3) * 4      # 20         |")
        print("| result = 2 ** (3 ** 2)    # 512        |")
        print("|                                         |")
        print("| # Complex expression                    |")
        print("| x = 5                                   |")
        print("| result = x > 3 and x < 10 or x == 0    |")
        print("|        # (x > 3 and x < 10) or x == 0  |")
        print("+-------------------------------------------+")

    def show_python_strings(self):
        """Shows Python String creation & manipulation"""
        print("\n" + "=" * 75)
        print(">> PYTHON STRING CREATION & MANIPULATION")
        print("=" * 75)
        print()
        print("Strings are sequences of characters in Python.")
        print()
        print("1. STRING CREATION:")
        print("+-------------------------------------------+")
        print("| # Single quotes                         |")
        print("| name = 'Alice'                          |")
        print("|                                         |")
        print("| # Double quotes                         |")
        print("| message = \"Hello World\"                 |")
        print("|                                         |")
        print("| # Triple quotes (multiline)             |")
        print("| text = '''This is a                     |")
        print("| multiline string'''                     |")
        print("+-------------------------------------------+")
        print()
        print("2. STRING OPERATIONS:")
        print("+-------------------------------------------+")
        print("| text = 'Hello World'                    |")
        print("|                                         |")
        print("| print(len(text))         # 11 (length) |")
        print("| print(text[0])           # 'H' (index) |")
        print("| print(text[-1])          # 'd' (last)  |")
        print("|                                         |")
        print("| # String is immutable                   |")
        print("| # text[0] = 'h'  # Error!               |")
        print("+-------------------------------------------+")
        print()
        print("3. BASIC STRING METHODS:")
        print("+-------------------------------------------+")
        print("| text = 'Hello World'                    |")
        print("|                                         |")
        print("| print(text.upper())      # HELLO WORLD |")
        print("| print(text.lower())      # hello world |")
        print("| print(text.title())      # Hello World |")
        print("| print(text.replace('World', 'Python'))  |")
        print("| # Output: Hello Python                  |")
        print("+-------------------------------------------+")

    def show_python_slicing(self):
        """Shows Python String slicing techniques"""
        print("\n" + "=" * 75)
        print(">> PYTHON STRING SLICING")
        print("=" * 75)
        print()
        print("String slicing extracts parts of strings using [start:stop:step].")
        print()
        print("1. BASIC SLICING:")
        print("+-------------------------------------------+")
        print("| text = 'Hello World'                    |")
        print("| #       0123456789...                   |")
        print("|                                         |")
        print("| print(text[0:5])         # Hello       |")
        print("| print(text[6:11])        # World       |")
        print("| print(text[:5])          # Hello       |")
        print("| print(text[6:])          # World       |")
        print("| print(text[:])           # Hello World |")
        print("+-------------------------------------------+")
        print()
        print("2. NEGATIVE INDEXING:")
        print("+-------------------------------------------+")
        print("| text = 'Python'                         |")
        print("| #       -6-5-4-3-2-1                    |")
        print("|                                         |")
        print("| print(text[-6:])         # Python      |")
        print("| print(text[-3:])         # hon         |")
        print("| print(text[:-3])         # Pyt         |")
        print("| print(text[-6:-3])       # Pyt         |")
        print("+-------------------------------------------+")
        print()
        print("3. STEP SLICING:")
        print("+-------------------------------------------+")
        print("| text = 'Programming'                    |")
        print("|                                         |")
        print("| print(text[::2])         # Pormin      |")
        print("| print(text[1::2])        # rgamn       |")
        print("| print(text[::-1])        # gnimmargorP |")
        print("| print(text[::3])         # Pormg       |")
        print("+-------------------------------------------+")

    def show_python_concatenation(self):
        """Shows Python String concatenation"""
        print("\n" + "=" * 75)
        print(">> PYTHON STRING CONCATENATION")
        print("=" * 75)
        print()
        print("String concatenation combines multiple strings.")
        print()
        print("1. USING + OPERATOR:")
        print("+-------------------------------------------+")
        print("| first = 'Hello'                         |")
        print("| last = 'World'                          |")
        print("| full = first + ' ' + last               |")
        print("| print(full)              # Hello World  |")
        print("+-------------------------------------------+")
        print()
        print("2. USING += OPERATOR:")
        print("+-------------------------------------------+")
        print("| message = 'Hello'                       |")
        print("| message += ' '                          |")
        print("| message += 'World'                      |")
        print("| print(message)           # Hello World  |")
        print("+-------------------------------------------+")
        print()
        print("3. USING JOIN() METHOD:")
        print("+-------------------------------------------+")
        print("| words = ['Hello', 'World', 'Python']    |")
        print("| sentence = ' '.join(words)              |")
        print("| print(sentence)          # Hello World Python |")
        print("|                                         |")
        print("| # Different separators                  |")
        print("| print('-'.join(words))   # Hello-World-Python |")
        print("| print(''.join(words))    # HelloWorldPython   |")
        print("+-------------------------------------------+")
        print()
        print("4. PERFORMANCE NOTE:")
        print("For many concatenations, join() is more efficient than +")

    def show_python_format_strings(self):
        """Shows Python Format strings (f-strings)"""
        print("\n" + "=" * 75)
        print(">> PYTHON FORMAT STRINGS (F-STRINGS)")
        print("=" * 75)
        print()
        print("F-strings provide easy string interpolation (Python 3.6+).")
        print()
        print("1. BASIC F-STRINGS:")
        print("+-------------------------------------------+")
        print("| name = 'Alice'                          |")
        print("| age = 30                                |")
        print("|                                         |")
        print("| message = f'My name is {name}'          |")
        print("| print(message)           # My name is Alice |")
        print("|                                         |")
        print("| info = f'{name} is {age} years old'     |")
        print("| print(info)              # Alice is 30 years old |")
        print("+-------------------------------------------+")
        print()
        print("2. EXPRESSIONS IN F-STRINGS:")
        print("+-------------------------------------------+")
        print("| x = 10                                  |")
        print("| y = 5                                   |")
        print("|                                         |")
        print("| result = f'{x} + {y} = {x + y}'         |")
        print("| print(result)            # 10 + 5 = 15  |")
        print("|                                         |")
        print("| name = 'bob'                            |")
        print("| print(f'Hello {name.title()}!')        |")
        print("| # Output: Hello Bob!                    |")
        print("+-------------------------------------------+")
        print()
        print("3. FORMATTING OPTIONS:")
        print("+-------------------------------------------+")
        print("| pi = 3.14159265359                      |")
        print("| number = 1234.567                       |")
        print("|                                         |")
        print("| print(f'{pi:.2f}')       # 3.14        |")
        print("| print(f'{pi:.4f}')       # 3.1416      |")
        print("| print(f'{number:,.2f}')  # 1,234.57    |")
        print("| print(f'{number:.2e}')   # 1.23e+03    |")
        print("+-------------------------------------------+")

    def show_python_escape_chars(self):
        """Shows Python Escape characters"""
        print("\n" + "=" * 75)
        print(">> PYTHON ESCAPE CHARACTERS")
        print("=" * 75)
        print()
        print("Escape characters represent special characters in strings.")
        print()
        print("1. COMMON ESCAPE SEQUENCES:")
        print("+-------------------------------------------+")
        print("| Escape  | Description       | Example     |")
        print("|---------|-------------------|-------------|")
        print("| \\n      | Newline           | 'Hi\\nBye'  |")
        print("| \\t      | Tab               | 'A\\tB'     |")
        print("| \\r      | Carriage return   | 'A\\rB'     |")
        print("| \\b      | Backspace         | 'AB\\bC'    |")
        print("| \\f      | Form feed         | 'A\\fB'     |")
        print("| \\v      | Vertical tab      | 'A\\vB'     |")
        print("|         |                   |             |")
        print("| \\\\      | Backslash         | 'C:\\\\path' |")
        print("| \\'      | Single quote      | 'I\\'m'     |")
        print("| \\\"      | Double quote      | '\"Hello\"'  |")
        print("+-------------------------------------------+")
        print()
        print("2. EXAMPLES:")
        print("+-------------------------------------------+")
        print("| # Newlines and tabs                     |")
        print("| print('Line 1\\nLine 2\\nLine 3')        |")
        print("| print('Name\\tAge\\tCity')               |")
        print("|                                         |")
        print("| # Quotes in strings                     |")
        print("| print('She said \"Hello\"')              |")
        print("| print(\"I\\'m learning Python\")            |")
        print("+-------------------------------------------+")
        print()
        print("3. RAW STRINGS:")
        print("+-------------------------------------------+")
        print("| # Use r'' to avoid escaping             |")
        print("| path = r'C:\\Users\\Documents\\file.txt'  |")
        print("| regex = r'\\d+\\w+'                      |")
        print("|                                         |")
        print("| # Without raw string:                   |")
        print("| path = 'C:\\\\Users\\\\Documents\\\\file.txt' |")
        print("+-------------------------------------------+")

    def show_python_string_methods(self):
        """Shows Python String methods"""
        print("\n" + "=" * 75)
        print(">> PYTHON STRING METHODS")
        print("=" * 75)
        print()
        print("Python strings have many built-in methods for manipulation.")
        print()
        print("1. CASE METHODS:")
        print("+-------------------------------------------+")
        print("| text = 'Hello World'                    |")
        print("|                                         |")
        print("| print(text.upper())      # HELLO WORLD |")
        print("| print(text.lower())      # hello world |")
        print("| print(text.title())      # Hello World |")
        print("| print(text.capitalize())  # Hello world|")
        print("| print(text.swapcase())    # hELLO wORLD |")
        print("+-------------------------------------------+")
        print()
        print("2. SEARCH METHODS:")
        print("+-------------------------------------------+")
        print("| text = 'Python Programming'             |")
        print("|                                         |")
        print("| print(text.find('Pro'))   # 7 (index)  |")
        print("| print(text.find('Java'))  # -1 (not found) |")
        print("| print(text.index('Pro'))  # 7 (index) |")
        print("| print(text.count('o'))    # 2 (occurrences) |")
        print("|                                         |")
        print("| print(text.startswith('Py')) # True    |")
        print("| print(text.endswith('ing'))  # True    |")
        print("+-------------------------------------------+")
        print()
        print("3. MODIFICATION METHODS:")
        print("+-------------------------------------------+")
        print("| text = '  Python  '                     |")
        print("|                                         |")
        print("| print(text.strip())       # 'Python'   |")
        print("| print(text.lstrip())      # 'Python  ' |")
        print("| print(text.rstrip())      # '  Python' |")
        print("|                                         |")
        print("| sentence = 'I love Java'                |")
        print("| print(sentence.replace('Java', 'Python')) |")
        print("| # Output: I love Python                 |")
        print("+-------------------------------------------+")
        print()
        print("4. SPLIT AND JOIN:")
        print("+-------------------------------------------+")
        print("| csv_data = 'apple,banana,cherry'        |")
        print("| fruits = csv_data.split(',')            |")
        print("| print(fruits)  # ['apple', 'banana', 'cherry'] |")
        print("|                                         |")
        print("| words = ['Hello', 'World']              |")
        print("| sentence = ' '.join(words)              |")
        print("| print(sentence)           # Hello World |")
        print("+-------------------------------------------+")

    def show_python_math_module(self):
        """Shows Python Math module & functions"""
        print("\n" + "=" * 75)
        print(">> PYTHON MATH MODULE & FUNCTIONS")
        print("=" * 75)
        print()
        print("The math module provides mathematical functions and constants.")
        print()
        print("1. IMPORTING MATH:")
        print("+-------------------------------------------+")
        print("| import math                             |")
        print("| # or                                    |")
        print("| from math import sqrt, pi, sin         |")
        print("+-------------------------------------------+")
        print()
        print("2. BASIC FUNCTIONS:")
        print("+-------------------------------------------+")
        print("| import math                             |")
        print("|                                         |")
        print("| print(math.sqrt(16))      # 4.0        |")
        print("| print(math.pow(2, 3))     # 8.0        |")
        print("| print(math.abs(-5))       # 5          |")
        print("| print(abs(-5))            # 5 (built-in) |")
        print("|                                         |")
        print("| # Rounding                              |")
        print("| print(math.ceil(4.3))     # 5          |")
        print("| print(math.floor(4.7))    # 4          |")
        print("| print(round(4.7))         # 5 (built-in) |")
        print("+-------------------------------------------+")
        print()
        print("3. TRIGONOMETRIC FUNCTIONS:")
        print("+-------------------------------------------+")
        print("| import math                             |")
        print("|                                         |")
        print("| angle = math.pi / 4  # 45 degrees      |")
        print("|                                         |")
        print("| print(math.sin(angle))    # ~0.707     |")
        print("| print(math.cos(angle))    # ~0.707     |")
        print("| print(math.tan(angle))    # ~1.0       |")
        print("|                                         |")
        print("| # Convert degrees to radians            |")
        print("| print(math.radians(180))  # 3.14159... |")
        print("| print(math.degrees(math.pi)) # 180.0   |")
        print("+-------------------------------------------+")
        print()
        print("4. CONSTANTS AND LOGARITHMS:")
        print("+-------------------------------------------+")
        print("| import math                             |")
        print("|                                         |")
        print("| print(math.pi)            # 3.14159... |")
        print("| print(math.e)             # 2.71828... |")
        print("|                                         |")
        print("| print(math.log(10))       # Natural log|")
        print("| print(math.log10(100))    # 2.0        |")
        print("| print(math.log(8, 2))     # 3.0 (log base 2) |")
        print("+-------------------------------------------+")

    def show_python_booleans(self):
        """Shows Python Boolean operations"""
        print("\n" + "=" * 75)
        print(">> PYTHON BOOLEAN OPERATIONS")
        print("=" * 75)
        print()
        print("Boolean values represent True or False in Python.")
        print()
        print("1. BOOLEAN VALUES:")
        print("+-------------------------------------------+")
        print("| # Boolean literals                      |")
        print("| is_active = True                        |")
        print("| is_complete = False                     |")
        print("|                                         |")
        print("| # Boolean from comparisons              |")
        print("| result = 5 > 3          # True         |")
        print("| check = 'a' in 'hello'  # False        |")
        print("+-------------------------------------------+")
        print()
        print("2. TRUTHY AND FALSY VALUES:")
        print("+-------------------------------------------+")
        print("| # Falsy values (evaluate to False):    |")
        print("| print(bool(False))       # False       |")
        print("| print(bool(0))           # False       |")
        print("| print(bool(0.0))         # False       |")
        print("| print(bool(''))          # False       |")
        print("| print(bool([]))          # False       |")
        print("| print(bool({}))          # False       |")
        print("| print(bool(None))        # False       |")
        print("|                                         |")
        print("| # Truthy values (evaluate to True):    |")
        print("| print(bool(1))           # True        |")
        print("| print(bool('hello'))     # True        |")
        print("| print(bool([1, 2, 3]))   # True        |")
        print("+-------------------------------------------+")
        print()
        print("3. BOOLEAN OPERATORS:")
        print("+-------------------------------------------+")
        print("| x = True                                |")
        print("| y = False                               |")
        print("|                                         |")
        print("| print(x and y)           # False       |")
        print("| print(x or y)            # True        |")
        print("| print(not x)             # False       |")
        print("|                                         |")
        print("| # Short-circuit evaluation              |")
        print("| print(False and print('Hi'))  # False  |")
        print("| # 'Hi' is not printed                  |")
        print("+-------------------------------------------+")