"""
Python Flow Control - Loops, conditions, and collection basics
"""


class PythonFlowControl:
    def __init__(self):
        pass

    def show_python_conditions(self):
        """Shows Python if-else conditional statements with examples"""
        print("\n" + "=" * 75)
        print(">> PYTHON IF...ELSE")
        print("=" * 75)
        print()
        print("Conditional statements execute code based on conditions.")
        print()
        print("1. BASIC IF STATEMENT:")
        print("+-------------------------------------------+")
        print("| age = 18                                |")
        print("|                                         |")
        print("| if age >= 18:                           |")
        print("|     print('You can vote!')             |")
        print("|                                         |")
        print("| # Multiple statements                   |")
        print("| score = 85                              |")
        print("| if score >= 60:                        |")
        print("|     print('Congratulations!')          |")
        print("|     print('You passed!')               |")
        print("+-------------------------------------------+")
        print()
        print("2. IF-ELSE STATEMENT:")
        print("+-------------------------------------------+")
        print("| temperature = 25                        |")
        print("|                                         |")
        print("| if temperature > 30:                    |")
        print("|     print('It\'s hot!')                 |")
        print("| else:                                   |")
        print("|     print('It\'s not too hot')          |")
        print("|                                         |")
        print("| # Nested conditions                     |")
        print("| x = 10                                  |")
        print("| if x > 0:                               |")
        print("|     if x % 2 == 0:                      |")
        print("|         print('Positive and even')      |")
        print("|     else:                               |")
        print("|         print('Positive and odd')       |")
        print("+-------------------------------------------+")
        print()
        print("3. ELIF (ELSE IF) STATEMENT:")
        print("+-------------------------------------------+")
        print("| grade = 85                              |")
        print("|                                         |")
        print("| if grade >= 90:                         |")
        print("|     letter = 'A'                        |")
        print("| elif grade >= 80:                       |")
        print("|     letter = 'B'                        |")
        print("| elif grade >= 70:                       |")
        print("|     letter = 'C'                        |")
        print("| elif grade >= 60:                       |")
        print("|     letter = 'D'                        |")
        print("| else:                                   |")
        print("|     letter = 'F'                        |")
        print("|                                         |")
        print("| print(f'Grade: {letter}')  # Grade: B  |")
        print("+-------------------------------------------+")

    def show_python_while(self):
        """Shows Python while loops with examples and control statements"""
        print("\n" + "=" * 75)
        print(">> WHILE LOOP")
        print("=" * 75)
        print()
        print("While loops repeat code as long as a condition is true.")
        print()
        print("1. BASIC WHILE LOOP:")
        print("+-------------------------------------------+")
        print("| # Count from 1 to 5                     |")
        print("| count = 1                               |")
        print("| while count <= 5:                       |")
        print("|     print(count)                        |")
        print("|     count += 1                          |")
        print("|                                         |")
        print("| # Output: 1 2 3 4 5                     |")
        print("|                                         |")
        print("| # Sum numbers until limit               |")
        print("| total = 0                               |")
        print("| num = 1                                 |")
        print("| while total < 100:                      |")
        print("|     total += num                        |")
        print("|     num += 1                            |")
        print("+-------------------------------------------+")
        print()
        print("2. BREAK AND CONTINUE:")
        print("+-------------------------------------------+")
        print("| # Using break to exit loop              |")
        print("| count = 0                               |")
        print("| while True:                             |")
        print("|     count += 1                          |")
        print("|     if count > 3:                       |")
        print("|         break  # Exit loop              |")
        print("|     print(count)  # Prints: 1 2 3       |")
        print("|                                         |")
        print("| # Using continue to skip iteration     |")
        print("| num = 0                                 |")
        print("| while num < 5:                          |")
        print("|     num += 1                            |")
        print("|     if num % 2 == 0:                    |")
        print("|         continue  # Skip even numbers   |")
        print("|     print(num)  # Prints: 1 3 5         |")
        print("+-------------------------------------------+")
        print()
        print("3. WHILE-ELSE:")
        print("+-------------------------------------------+")
        print("| # else executes when loop completes     |")
        print("| count = 0                               |")
        print("| while count < 3:                        |")
        print("|     print(f'Count: {count}')           |")
        print("|     count += 1                          |")
        print("| else:                                   |")
        print("|     print('Loop completed!')           |")
        print("|                                         |")
        print("| # else does NOT run if loop breaks      |")
        print("| while count < 10:                       |")
        print("|     if count == 5:                      |")
        print("|         break                           |")
        print("|     count += 1                          |")
        print("| else:                                   |")
        print("|     print('This will not print')       |")
        print("+-------------------------------------------+")

    def show_python_for(self):
        """Shows Python for loops with examples for ranges and sequences"""
        print("\n" + "=" * 75)
        print(">> FOR LOOP")
        print("=" * 75)
        print()
        print("For loops iterate over sequences (lists, strings, ranges).")
        print()
        print("1. ITERATING OVER RANGES:")
        print("+-------------------------------------------+")
        print("| # range(stop)                           |")
        print("| for i in range(5):                      |")
        print("|     print(i)  # 0, 1, 2, 3, 4          |")
        print("|                                         |")
        print("| # range(start, stop)                    |")
        print("| for i in range(2, 6):                   |")
        print("|     print(i)  # 2, 3, 4, 5             |")
        print("|                                         |")
        print("| # range(start, stop, step)              |")
        print("| for i in range(0, 10, 2):               |")
        print("|     print(i)  # 0, 2, 4, 6, 8          |")
        print("+-------------------------------------------+")
        print()
        print("2. ITERATING OVER SEQUENCES:")
        print("+-------------------------------------------+")
        print("| # Iterate over string                   |")
        print("| for char in 'Python':                   |")
        print("|     print(char)  # P y t h o n          |")
        print("|                                         |")
        print("| # Iterate over list                     |")
        print("| fruits = ['apple', 'banana', 'cherry']  |")
        print("| for fruit in fruits:                    |")
        print("|     print(fruit)                        |")
        print("|                                         |")
        print("| # Enumerate for index and value         |")
        print("| for index, fruit in enumerate(fruits):  |")
        print("|     print(f'{index}: {fruit}')         |")
        print("+-------------------------------------------+")
        print()
        print("3. NESTED LOOPS:")
        print("+-------------------------------------------+")
        print("| # Multiplication table                  |")
        print("| for i in range(1, 4):                   |")
        print("|     for j in range(1, 4):               |")
        print("|         print(f'{i} x {j} = {i*j}')     |")
        print("|                                         |")
        print("| # Creating a matrix                     |")
        print("| matrix = []                             |")
        print("| for i in range(3):                      |")
        print("|     row = []                            |")
        print("|     for j in range(3):                  |")
        print("|         row.append(i * j)               |")
        print("|     matrix.append(row)                  |")
        print("+-------------------------------------------+")

    def show_python_nested_loops(self):
        """Shows Python nested loop structures"""
        print("\n" + "=" * 75)
        print(">> NESTED LOOPS")
        print("=" * 75)
        print()
        print("Nested loops are loops inside other loops.")
        print()
        print("1. BASIC NESTED LOOPS:")
        print("+-------------------------------------------+")
        print("| # Print a pattern                       |")
        print("| for i in range(3):                      |")
        print("|     for j in range(3):                  |")
        print("|         print('*', end=' ')             |")
        print("|     print()  # New line                 |")
        print("|                                         |")
        print("| # Output:                               |")
        print("| # * * *                                 |")
        print("| # * * *                                 |")
        print("| # * * *                                 |")
        print("+-------------------------------------------+")
        print()
        print("2. TRIANGLE PATTERNS:")
        print("+-------------------------------------------+")
        print("| # Right triangle                        |")
        print("| for i in range(1, 5):                   |")
        print("|     for j in range(i):                  |")
        print("|         print('*', end='')              |")
        print("|     print()                             |")
        print("|                                         |")
        print("| # Output:                               |")
        print("| # *                                     |")
        print("| # **                                    |")
        print("| # ***                                   |")
        print("| # ****                                  |")
        print("+-------------------------------------------+")
        print()
        print("3. COMPLEX NESTED PATTERNS:")
        print("+-------------------------------------------+")
        print("| # Number pyramid                        |")
        print("| rows = 4                                |")
        print("| for i in range(1, rows + 1):            |")
        print("|     # Print leading spaces              |")
        print("|     for j in range(rows - i):           |")
        print("|         print(' ', end='')              |")
        print("|     # Print numbers                     |")
        print("|     for k in range(2 * i - 1):          |")
        print("|         print(i, end='')                |")
        print("|     print()                             |")
        print("|                                         |")
        print("| # Output:                               |")
        print("| #    1                                  |")
        print("| #   222                                 |")
        print("| #  33333                                |")
        print("| # 4444444                               |")
        print("+-------------------------------------------+")

    def show_python_for_each(self):
        """Shows Python for-each loop patterns"""
        print("\n" + "=" * 75)
        print(">> FOR-EACH LOOP PATTERNS")
        print("=" * 75)
        print()
        print("Python's for loop naturally iterates over collections (for-each style).")
        print()
        print("1. BASIC FOR-EACH:")
        print("+-------------------------------------------+")
        print("| # Iterate over list elements             |")
        print("| fruits = ['apple', 'banana', 'cherry']  |")
        print("| for fruit in fruits:                    |")
        print("|     print(f'I like {fruit}')           |")
        print("|                                         |")
        print("| # Iterate over string characters         |")
        print("| for char in 'Hello':                    |")
        print("|     print(char.upper())                 |")
        print("|                                         |")
        print("| # Iterate over dictionary keys           |")
        print("| person = {'name': 'Alice', 'age': 30}   |")
        print("| for key in person:                      |")
        print("|     print(f'{key}: {person[key]}')     |")
        print("+-------------------------------------------+")
        print()
        print("2. ENUMERATE FOR INDEX AND VALUE:")
        print("+-------------------------------------------+")
        print("| colors = ['red', 'green', 'blue']       |")
        print("|                                         |")
        print("| # Get both index and value              |")
        print("| for index, color in enumerate(colors):  |")
        print("|     print(f'{index}: {color}')         |")
        print("|                                         |")
        print("| # Start enumeration from 1              |")
        print("| for num, color in enumerate(colors, 1): |")
        print("|     print(f'{num}. {color}')           |")
        print("+-------------------------------------------+")
        print()
        print("3. ITERATING OVER MULTIPLE SEQUENCES:")
        print("+-------------------------------------------+")
        print("| names = ['Alice', 'Bob', 'Charlie']     |")
        print("| ages = [25, 30, 35]                     |")
        print("|                                         |")
        print("| # zip() combines multiple iterables     |")
        print("| for name, age in zip(names, ages):      |")
        print("|     print(f'{name} is {age} years old') |")
        print("|                                         |")
        print("| # Iterate over dictionary items          |")
        print("| scores = {'Alice': 85, 'Bob': 92}       |")
        print("| for name, score in scores.items():      |")
        print("|     print(f'{name}: {score}')          |")
        print("+-------------------------------------------+")

    def show_python_break_continue(self):
        """Shows Python Break & Continue statements"""
        print("\n" + "=" * 75)
        print(">> BREAK & CONTINUE STATEMENTS")
        print("=" * 75)
        print()
        print("Break and continue control loop execution.")
        print()
        print("1. BREAK STATEMENT:")
        print("+-------------------------------------------+")
        print("| # Exit loop when condition is met       |")
        print("| numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]   |")
        print("| for num in numbers:                     |")
        print("|     if num > 5:                         |")
        print("|         break  # Exit loop              |")
        print("|     print(num)  # Prints: 1 2 3 4 5     |")
        print("|                                         |")
        print("| # Find first even number                |")
        print("| numbers = [1, 3, 7, 8, 9]               |")
        print("| for num in numbers:                     |")
        print("|     if num % 2 == 0:                    |")
        print("|         print(f'Found even: {num}')     |")
        print("|         break                           |")
        print("|     print(f'Checking {num}')           |")
        print("+-------------------------------------------+")
        print()
        print("2. CONTINUE STATEMENT:")
        print("+-------------------------------------------+")
        print("| # Skip even numbers                     |")
        print("| for i in range(1, 11):                  |")
        print("|     if i % 2 == 0:                      |")
        print("|         continue  # Skip rest of loop   |")
        print("|     print(i)  # Prints: 1 3 5 7 9       |")
        print("|                                         |")
        print("| # Process only valid data               |")
        print("| data = ['apple', '', 'banana', '', 'cherry'] |")
        print("| for item in data:                       |")
        print("|     if not item:  # Skip empty strings  |")
        print("|         continue                        |")
        print("|     print(f'Processing: {item}')       |")
        print("+-------------------------------------------+")
        print()
        print("3. NESTED LOOPS WITH BREAK/CONTINUE:")
        print("+-------------------------------------------+")
        print("| # break only exits innermost loop       |")
        print("| for i in range(3):                      |")
        print("|     print(f'Outer loop: {i}')          |")
        print("|     for j in range(3):                  |")
        print("|         if j == 1:                      |")
        print("|             break  # Exit inner loop    |")
        print("|         print(f'  Inner loop: {j}')     |")
        print("|                                         |")
        print("| # To break outer loop, use flag         |")
        print("| found = False                           |")
        print("| for i in range(3):                      |")
        print("|     if found:                           |")
        print("|         break                           |")
        print("|     for j in range(3):                  |")
        print("|         if i == 1 and j == 1:           |")
        print("|             found = True                |")
        print("|             break                       |")
        print("+-------------------------------------------+")

    def show_python_tuples(self):
        """Shows Python Tuples & immutable sequences"""
        print("\n" + "=" * 75)
        print(">> PYTHON TUPLES & IMMUTABLE SEQUENCES")
        print("=" * 75)
        print()
        print("Tuples are ordered, immutable collections of items.")
        print()
        print("1. CREATING TUPLES:")
        print("+-------------------------------------------+")
        print("| # Using parentheses                     |")
        print("| coordinates = (3, 5)                    |")
        print("| colors = ('red', 'green', 'blue')       |")
        print("|                                         |")
        print("| # Without parentheses (tuple packing)   |")
        print("| point = 10, 20                          |")
        print("| print(type(point))  # <class 'tuple'>   |")
        print("|                                         |")
        print("| # Single item tuple (note the comma)    |")
        print("| single = (42,)                          |")
        print("| not_tuple = (42)   # This is just int   |")
        print("|                                         |")
        print("| # Empty tuple                           |")
        print("| empty = ()                              |")
        print("+-------------------------------------------+")
        print()
        print("2. ACCESSING TUPLE ELEMENTS:")
        print("+-------------------------------------------+")
        print("| rgb = (255, 128, 0)                     |")
        print("|                                         |")
        print("| # Indexing (0-based)                    |")
        print("| print(rgb[0])        # 255              |")
        print("| print(rgb[-1])       # 0 (last element)|")
        print("|                                         |")
        print("| # Slicing                               |")
        print("| numbers = (1, 2, 3, 4, 5)               |")
        print("| print(numbers[1:4])  # (2, 3, 4)        |")
        print("| print(numbers[:3])   # (1, 2, 3)        |")
        print("|                                         |")
        print("| # Tuple unpacking                       |")
        print("| x, y, z = rgb                           |")
        print("| print(f'R:{x}, G:{y}, B:{z}')          |")
        print("+-------------------------------------------+")
        print()
        print("3. TUPLE METHODS AND OPERATIONS:")
        print("+-------------------------------------------+")
        print("| numbers = (1, 2, 3, 2, 4, 2)            |")
        print("|                                         |")
        print("| # Tuple methods                         |")
        print("| print(numbers.count(2))  # 3 (count occurrences) |")
        print("| print(numbers.index(3))  # 2 (find index) |")
        print("|                                         |")
        print("| # Tuple operations                      |")
        print("| print(len(numbers))   # 6 (length)      |")
        print("| print(2 in numbers)   # True (membership) |")
        print("| print(max(numbers))   # 4 (maximum)     |")
        print("| print(min(numbers))   # 1 (minimum)     |")
        print("|                                         |")
        print("| # Concatenation and repetition          |")
        print("| tuple1 = (1, 2)                         |")
        print("| tuple2 = (3, 4)                         |")
        print("| combined = tuple1 + tuple2  # (1,2,3,4) |")
        print("| repeated = tuple1 * 3       # (1,2,1,2,1,2) |")
        print("+-------------------------------------------+")

    def show_python_lists(self):
        """Shows Python Lists & mutable sequences"""
        print("\n" + "=" * 75)
        print(">> PYTHON LISTS & MUTABLE SEQUENCES")
        print("=" * 75)
        print()
        print("Lists are ordered, mutable collections of items.")
        print()
        print("1. CREATING LISTS:")
        print("+-------------------------------------------+")
        print("| # Using square brackets                  |")
        print("| fruits = ['apple', 'banana', 'cherry']  |")
        print("| numbers = [1, 2, 3, 4, 5]               |")
        print("| mixed = [1, 'hello', 3.14, True]        |")
        print("|                                         |")
        print("| # Empty list                            |")
        print("| empty_list = []                         |")
        print("| also_empty = list()                     |")
        print("|                                         |")
        print("| # List from other iterables             |")
        print("| from_string = list('hello')  # ['h','e','l','l','o'] |")
        print("| from_range = list(range(5))  # [0,1,2,3,4] |")
        print("+-------------------------------------------+")
        print()
        print("2. ACCESSING AND MODIFYING:")
        print("+-------------------------------------------+")
        print("| colors = ['red', 'green', 'blue']       |")
        print("|                                         |")
        print("| # Indexing and slicing                  |")
        print("| print(colors[0])      # 'red'           |")
        print("| print(colors[-1])     # 'blue'          |")
        print("| print(colors[1:3])    # ['green', 'blue'] |")
        print("|                                         |")
        print("| # Modifying elements                    |")
        print("| colors[0] = 'yellow'                    |")
        print("| print(colors)  # ['yellow', 'green', 'blue'] |")
        print("|                                         |")
        print("| # Modifying slices                      |")
        print("| colors[1:3] = ['orange', 'purple']      |")
        print("| print(colors)  # ['yellow', 'orange', 'purple'] |")
        print("+-------------------------------------------+")
        print()
        print("3. LIST METHODS:")
        print("+-------------------------------------------+")
        print("| items = ['a', 'b', 'c']                 |")
        print("|                                         |")
        print("| # Adding elements                       |")
        print("| items.append('d')        # ['a','b','c','d'] |")
        print("| items.insert(1, 'x')     # ['a','x','b','c','d'] |")
        print("| items.extend(['e', 'f']) # Add multiple |")
        print("|                                         |")
        print("| # Removing elements                     |")
        print("| items.remove('x')        # Remove first 'x' |")
        print("| last = items.pop()       # Remove & return last |")
        print("| second = items.pop(1)    # Remove & return index 1 |")
        print("| del items[0]             # Delete by index |")
        print("| items.clear()            # Remove all   |")
        print("|                                         |")
        print("| # Other useful methods                  |")
        print("| numbers = [3, 1, 4, 1, 5]               |")
        print("| numbers.sort()           # [1,1,3,4,5]  |")
        print("| numbers.reverse()        # [5,4,3,1,1]  |")
        print("| count_1 = numbers.count(1) # 2         |")
        print("+-------------------------------------------+")

    def show_python_sets(self):
        """Shows Python Sets & unique collections"""
        print("\n" + "=" * 75)
        print(">> PYTHON SETS & UNIQUE COLLECTIONS")
        print("=" * 75)
        print()
        print("Sets are unordered collections of unique items.")
        print()
        print("1. CREATING SETS:")
        print("+-------------------------------------------+")
        print("| # Using curly braces                    |")
        print("| colors = {'red', 'green', 'blue'}       |")
        print("| numbers = {1, 2, 3, 4, 5}               |")
        print("|                                         |")
        print("| # From other iterables                  |")
        print("| from_list = set([1, 2, 2, 3, 3])        |")
        print("| print(from_list)      # {1, 2, 3}       |")
        print("|                                         |")
        print("| from_string = set('hello')              |")
        print("| print(from_string)    # {'h','e','l','o'} |")
        print("|                                         |")
        print("| # Empty set (must use set())             |")
        print("| empty_set = set()     # NOT {}          |")
        print("| empty_dict = {}       # This is a dict! |")
        print("+-------------------------------------------+")
        print()
        print("2. SET OPERATIONS:")
        print("+-------------------------------------------+")
        print("| fruits = {'apple', 'banana', 'cherry'}  |")
        print("|                                         |")
        print("| # Adding elements                       |")
        print("| fruits.add('date')                      |")
        print("| fruits.update(['elderberry', 'fig'])    |")
        print("|                                         |")
        print("| # Removing elements                     |")
        print("| fruits.remove('banana')   # Raises KeyError if not found |")
        print("| fruits.discard('grape')   # No error if not found |")
        print("| item = fruits.pop()       # Remove & return random |")
        print("|                                         |")
        print("| # Membership testing                    |")
        print("| print('apple' in fruits)  # True        |")
        print("| print('grape' not in fruits) # True    |")
        print("+-------------------------------------------+")
        print()
        print("3. SET MATHEMATICS:")
        print("+-------------------------------------------+")
        print("| set1 = {1, 2, 3, 4}                     |")
        print("| set2 = {3, 4, 5, 6}                     |")
        print("|                                         |")
        print("| # Union (all elements from both sets)   |")
        print("| union = set1 | set2      # {1,2,3,4,5,6} |")
        print("| union = set1.union(set2)  # Same        |")
        print("|                                         |")
        print("| # Intersection (common elements)        |")
        print("| inter = set1 & set2      # {3, 4}       |")
        print("| inter = set1.intersection(set2) # Same  |")
        print("|                                         |")
        print("| # Difference (in set1 but not set2)     |")
        print("| diff = set1 - set2       # {1, 2}       |")
        print("| diff = set1.difference(set2) # Same     |")
        print("|                                         |")
        print("| # Symmetric difference (not in both)    |")
        print("| sym_diff = set1 ^ set2   # {1, 2, 5, 6} |")
        print("|                                         |")
        print("| # Subset/Superset testing               |")
        print("| print({1, 2}.issubset(set1))  # True    |")
        print("| print(set1.issuperset({1, 2})) # True  |")
        print("+-------------------------------------------+")

    def show_python_dictionaries(self):
        """Shows Python Dictionaries & key-value pairs"""
        print("\n" + "=" * 75)
        print(">> PYTHON DICTIONARIES & KEY-VALUE PAIRS")
        print("=" * 75)
        print()
        print("Dictionaries store data as key-value pairs (mappings).")
        print()
        print("1. CREATING DICTIONARIES:")
        print("+-------------------------------------------+")
        print("| # Using curly braces                    |")
        print("| person = {'name': 'Alice', 'age': 30}   |")
        print("| scores = {'math': 95, 'english': 87}    |")
        print("|                                         |")
        print("| # Using dict() constructor              |")
        print("| person2 = dict(name='Bob', age=25)      |")
        print("| from_pairs = dict([('a', 1), ('b', 2)]) |")
        print("|                                         |")
        print("| # Empty dictionary                      |")
        print("| empty_dict = {}                         |")
        print("| also_empty = dict()                     |")
        print("+-------------------------------------------+")
        print()
        print("2. ACCESSING AND MODIFYING:")
        print("+-------------------------------------------+")
        print("| student = {'name': 'Charlie', 'grade': 85} |")
        print("|                                         |")
        print("| # Accessing values                      |")
        print("| print(student['name'])    # 'Charlie'   |")
        print("| print(student.get('age', 0)) # 0 (default) |")
        print("|                                         |")
        print("| # Modifying values                      |")
        print("| student['grade'] = 90                   |")
        print("| student['age'] = 20      # Add new key  |")
        print("|                                         |")
        print("| # Removing items                        |")
        print("| del student['grade']     # Remove key   |")
        print("| age = student.pop('age', 0)  # Remove & return |")
        print("| item = student.popitem()  # Remove any  |")
        print("+-------------------------------------------+")
        print()
        print("3. DICTIONARY METHODS:")
        print("+-------------------------------------------+")
        print("| data = {'a': 1, 'b': 2, 'c': 3}         |")
        print("|                                         |")
        print("| # Getting keys, values, items           |")
        print("| print(list(data.keys()))    # ['a','b','c'] |")
        print("| print(list(data.values()))  # [1, 2, 3] |")
        print("| print(list(data.items()))   # [('a',1),('b',2),('c',3)] |")
        print("|                                         |")
        print("| # Iterating over dictionary             |")
        print("| for key in data:                        |")
        print("|     print(f'{key}: {data[key]}')       |")
        print("|                                         |")
        print("| for key, value in data.items():         |")
        print("|     print(f'{key}: {value}')           |")
        print("|                                         |")
        print("| # Updating dictionary                   |")
        print("| data.update({'d': 4, 'e': 5})           |")
        print("| data.update(f=6, g=7)                   |")
        print("|                                         |")
        print("| # Other useful methods                  |")
        print("| copy = data.copy()       # Shallow copy |")
        print("| data.clear()             # Remove all   |")
        print("|                                         |")
        print("| # Dictionary comprehension              |")
        print("| squares = {x: x**2 for x in range(5)}   |")
        print("| # Result: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16} |")
        print("+-------------------------------------------+")