class PythonDataStructures:
    def __init__(self):
        pass

    def show_python_list_advanced(self):
        """Shows advanced Python lists and arrays implementation and usage"""
        print("\n" + "=" * 75)
        print(">> ADVANCED LISTS AND ARRAYS")
        print("=" * 75)
        print()
        print("Lists and arrays are fundamental data structures for storing collections.")
        print()
        print("1. PYTHON LISTS:")
        print("+-------------------------------------------+")
        print("| # Dynamic arrays in Python              |")
        print("| numbers = [1, 2, 3, 4, 5]              |")
        print("| mixed = ['hello', 42, 3.14, True]       |")
        print("|                                         |")
        print("| # List operations                       |")
        print("| numbers.append(6)       # Add to end    |")
        print("| numbers.insert(0, 0)    # Insert at index |")
        print("| numbers.remove(3)       # Remove first 3 |")
        print("| last = numbers.pop()    # Remove last   |")
        print("|                                         |")
        print("| # List comprehensions                   |")
        print("| squares = [x**2 for x in range(10)]     |")
        print("| evens = [x for x in numbers if x % 2 == 0] |")
        print("+-------------------------------------------+")
        print()
        print("2. NUMPY ARRAYS:")
        print("+-------------------------------------------+")
        print("| import numpy as np                      |")
        print("|                                         |")
        print("| # Creating arrays                       |")
        print("| arr = np.array([1, 2, 3, 4, 5])         |")
        print("| zeros = np.zeros(5)     # [0. 0. 0. 0. 0.] |")
        print("| ones = np.ones(3)       # [1. 1. 1.]    |")
        print("| range_arr = np.arange(0, 10, 2)  # [0 2 4 6 8] |")
        print("|                                         |")
        print("| # Array operations (vectorized)         |")
        print("| arr2 = arr * 2          # [2 4 6 8 10]  |")
        print("| arr3 = arr + arr2       # [3 6 9 12 15] |")
        print("| mean_val = np.mean(arr) # 3.0           |")
        print("+-------------------------------------------+")
        print()
        print("3. MULTIDIMENSIONAL ARRAYS:")
        print("+-------------------------------------------+")
        print("| # 2D arrays (matrices)                  |")
        print("| matrix = np.array([[1, 2, 3],           |")
        print("|                    [4, 5, 6],           |")
        print("|                    [7, 8, 9]])          |")
        print("|                                         |")
        print("| # Array properties                      |")
        print("| print(matrix.shape)     # (3, 3)       |")
        print("| print(matrix.size)      # 9            |")
        print("| print(matrix.dtype)     # int64         |")
        print("|                                         |")
        print("| # Indexing and slicing                  |")
        print("| print(matrix[0, 1])     # 2 (row 0, col 1) |")
        print("| print(matrix[:, 1])     # [2 5 8] (col 1) |")
        print("| print(matrix[1, :])     # [4 5 6] (row 1) |")
        print("+-------------------------------------------+")

    def show_python_dict_advanced(self):
        """Shows advanced Python dictionaries and hash table concepts"""
        print("\n" + "=" * 75)
        print(">> ADVANCED DICTIONARIES & HASH TABLES")
        print("=" * 75)
        print()
        print("Hash tables provide fast key-value lookups using hashing.")
        print()
        print("1. PYTHON DICTIONARIES (HASH TABLES):")
        print("+-------------------------------------------+")
        print("| # Built-in hash table implementation    |")
        print("| phone_book = {                          |")
        print("|     'Alice': '555-1234',                |")
        print("|     'Bob': '555-5678',                  |")
        print("|     'Charlie': '555-9012'               |")
        print("| }                                       |")
        print("|                                         |")
        print("| # O(1) average time complexity          |")
        print("| print(phone_book['Alice'])  # '555-1234' |")
        print("| phone_book['David'] = '555-3456'        |")
        print("| del phone_book['Bob']                   |")
        print("+-------------------------------------------+")
        print()
        print("2. CUSTOM HASH TABLE:")
        print("+-------------------------------------------+")
        print("| class HashTable:                        |")
        print("|     def __init__(self, size=10):        |")
        print("|         self.size = size                |")
        print("|         self.table = [[] for _ in range(size)] |")
        print("|                                         |")
        print("|     def _hash(self, key):               |")
        print("|         return hash(key) % self.size    |")
        print("|                                         |")
        print("|     def put(self, key, value):          |")
        print("|         hash_key = self._hash(key)      |")
        print("|         bucket = self.table[hash_key]   |")
        print("|         for i, (k, v) in enumerate(bucket): |")
        print("|             if k == key:                |")
        print("|                 bucket[i] = (key, value) |")
        print("|                 return                  |")
        print("|         bucket.append((key, value))    |")
        print("|                                         |")
        print("|     def get(self, key):                 |")
        print("|         hash_key = self._hash(key)      |")
        print("|         bucket = self.table[hash_key]   |")
        print("|         for k, v in bucket:             |")
        print("|             if k == key:                |")
        print("|                 return v                |")
        print("|         raise KeyError(key)             |")
        print("+-------------------------------------------+")
        print()
        print("3. ADVANCED DICTIONARY FEATURES:")
        print("+-------------------------------------------+")
        print("| from collections import defaultdict, OrderedDict |")
        print("|                                         |")
        print("| # defaultdict - automatic default values |")
        print("| dd = defaultdict(list)                  |")
        print("| dd['fruits'].append('apple')            |")
        print("| dd['fruits'].append('banana')           |")
        print("|                                         |")
        print("| # OrderedDict - preserves insertion order |")
        print("| od = OrderedDict()                      |")
        print("| od['first'] = 1                         |")
        print("| od['second'] = 2                        |")
        print("|                                         |")
        print("| # Counter - counting hashable objects   |")
        print("| from collections import Counter          |")
        print("| counter = Counter('hello world')        |")
        print("| print(counter['l'])  # 3                |")
        print("+-------------------------------------------+")

    def show_python_set_advanced(self):
        """Shows advanced Python sets and mathematical operations"""
        print("\n" + "=" * 75)
        print(">> ADVANCED SETS & MATHEMATICAL OPERATIONS")
        print("=" * 75)
        print()
        print("Sets provide unique collections with mathematical set operations.")
        print()
        print("1. ADVANCED SET OPERATIONS:")
        print("+-------------------------------------------+")
        print("| set1 = {1, 2, 3, 4, 5}                  |")
        print("| set2 = {4, 5, 6, 7, 8}                  |")
        print("|                                         |")
        print("| # Union - all elements from both sets   |")
        print("| union = set1 | set2      # {1,2,3,4,5,6,7,8} |")
        print("| union = set1.union(set2)  # Same        |")
        print("|                                         |")
        print("| # Intersection - common elements        |")
        print("| inter = set1 & set2      # {4, 5}       |")
        print("| inter = set1.intersection(set2) # Same  |")
        print("|                                         |")
        print("| # Difference - in set1 but not set2     |")
        print("| diff = set1 - set2       # {1, 2, 3}    |")
        print("| diff = set1.difference(set2) # Same     |")
        print("|                                         |")
        print("| # Symmetric difference - not in both    |")
        print("| sym_diff = set1 ^ set2   # {1, 2, 3, 6, 7, 8} |")
        print("|                                         |")
        print("| # Subset/Superset testing               |")
        print("| print({1, 2}.issubset(set1))  # True    |")
        print("| print(set1.issuperset({1, 2})) # True  |")
        print("+-------------------------------------------+")
        print()
        print("2. FROZEN SETS - IMMUTABLE SETS:")
        print("+-------------------------------------------+")
        print("| # Frozen sets are immutable             |")
        print("| fs1 = frozenset([1, 2, 3])              |")
        print("| fs2 = frozenset([2, 3, 4])              |")
        print("|                                         |")
        print("| # Can be used as dictionary keys         |")
        print("| dict_with_set_keys = {                   |")
        print("|     fs1: 'first set',                   |")
        print("|     fs2: 'second set'                   |")
        print("| }                                       |")
        print("|                                         |")
        print("| # Set operations work with frozen sets   |")
        print("| union_fs = fs1 | fs2     # frozenset({1, 2, 3, 4}) |")
        print("| # fs1.add(4)  # AttributeError - immutable |")
        print("+-------------------------------------------+")
        print()
        print("3. PRACTICAL SET APPLICATIONS:")
        print("+-------------------------------------------+")
        print("| # Remove duplicates from list           |")
        print("| numbers = [1, 2, 2, 3, 3, 3, 4]         |")
        print("| unique = list(set(numbers))  # [1, 2, 3, 4] |")
        print("|                                         |")
        print("| # Find common elements in lists         |")
        print("| list1 = ['a', 'b', 'c', 'd']            |")
        print("| list2 = ['c', 'd', 'e', 'f']            |")
        print("| common = set(list1) & set(list2)  # {'c', 'd'} |")
        print("|                                         |")
        print("| # Check if lists have any common elements |")
        print("| has_common = bool(set(list1) & set(list2)) |")
        print("|                                         |")
        print("| # Fast membership testing               |")
        print("| large_set = set(range(1000000))         |")
        print("| print(500000 in large_set)  # Very fast |")
        print("+-------------------------------------------+")

    def show_python_tuple_advanced(self):
        """Shows advanced Python tuple features and named tuples"""
        print("\n" + "=" * 75)
        print(">> ADVANCED TUPLES & NAMED TUPLES")
        print("=" * 75)
        print()
        print("Tuples are immutable sequences with advanced features.")
        print()
        print("1. ADVANCED TUPLE OPERATIONS:")
        print("+-------------------------------------------+")
        print("| # Tuple unpacking with asterisk         |")
        print("| numbers = (1, 2, 3, 4, 5)               |")
        print("| first, *middle, last = numbers          |")
        print("| print(first)    # 1                     |")
        print("| print(middle)   # [2, 3, 4]             |")
        print("| print(last)     # 5                     |")
        print("|                                         |")
        print("| # Nested tuple unpacking                |")
        print("| nested = ((1, 2), (3, 4), (5, 6))       |")
        print("| for x, y in nested:                     |")
        print("|     print(f'{x}, {y}')  # 1, 2 etc.    |")
        print("|                                         |")
        print("| # Tuple as function arguments           |")
        print("| def add_three(a, b, c):                 |")
        print("|     return a + b + c                    |")
        print("| args = (1, 2, 3)                        |")
        print("| result = add_three(*args)  # 6          |")
        print("+-------------------------------------------+")
        print()
        print("2. NAMED TUPLES:")
        print("+-------------------------------------------+")
        print("| from collections import namedtuple      |")
        print("|                                         |")
        print("| # Define a named tuple                  |")
        print("| Point = namedtuple('Point', ['x', 'y']) |")
        print("| Person = namedtuple('Person', 'name age city') |")
        print("|                                         |")
        print("| # Create instances                      |")
        print("| p1 = Point(3, 4)                        |")
        print("| p2 = Point(x=1, y=2)                    |")
        print("|                                         |")
        print("| person = Person('Alice', 30, 'New York') |")
        print("|                                         |")
        print("| # Access by name or index               |")
        print("| print(p1.x)      # 3 (by name)         |")
        print("| print(p1[0])     # 3 (by index)        |")
        print("| print(person.name)  # 'Alice'          |")
        print("+-------------------------------------------+")
        print()
        print("3. NAMED TUPLE METHODS:")
        print("+-------------------------------------------+")
        print("| # Named tuple methods                   |")
        print("| person = Person('Bob', 25, 'Boston')    |")
        print("|                                         |")
        print("| # _replace() creates new instance       |")
        print("| older_person = person._replace(age=26)  |")
        print("|                                         |")
        print("| # _asdict() converts to dictionary      |")
        print("| person_dict = person._asdict()          |")
        print("| # {'name': 'Bob', 'age': 25, 'city': 'Boston'} |")
        print("|                                         |")
        print("| # _fields shows field names             |")
        print("| print(Person._fields)  # ('name', 'age', 'city') |")
        print("|                                         |")
        print("| # _make() creates from iterable         |")
        print("| data = ['Charlie', 35, 'Chicago']       |")
        print("| person = Person._make(data)             |")
        print("+-------------------------------------------+")

    def show_python_comprehensions(self):
        """Shows Python list, dict, and set comprehensions"""
        print("\n" + "=" * 75)
        print(">> PYTHON COMPREHENSIONS")
        print("=" * 75)
        print()
        print("Comprehensions provide concise ways to create collections.")
        print()
        print("1. LIST COMPREHENSIONS:")
        print("+-------------------------------------------+")
        print("| # Basic list comprehension              |")
        print("| squares = [x**2 for x in range(10)]     |")
        print("| # [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]   |")
        print("|                                         |")
        print("| # With condition                        |")
        print("| evens = [x for x in range(20) if x % 2 == 0] |")
        print("| # [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]   |")
        print("|                                         |")
        print("| # Multiple conditions                   |")
        print("| filtered = [x for x in range(100)       |")
        print("|            if x % 2 == 0 if x % 5 == 0] |")
        print("| # [0, 10, 20, 30, 40, 50, 60, 70, 80, 90] |")
        print("|                                         |")
        print("| # Nested loops                          |")
        print("| matrix = [[i*j for j in range(1, 4)]    |")
        print("|          for i in range(1, 4)]         |")
        print("| # [[1, 2, 3], [2, 4, 6], [3, 6, 9]]     |")
        print("+-------------------------------------------+")
        print()
        print("2. DICTIONARY COMPREHENSIONS:")
        print("+-------------------------------------------+")
        print("| # Basic dict comprehension              |")
        print("| squares_dict = {x: x**2 for x in range(5)} |")
        print("| # {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}       |")
        print("|                                         |")
        print("| # From two lists                        |")
        print("| keys = ['a', 'b', 'c']                  |")
        print("| values = [1, 2, 3]                      |")
        print("| combined = {k: v for k, v in zip(keys, values)} |")
        print("| # {'a': 1, 'b': 2, 'c': 3}             |")
        print("|                                         |")
        print("| # With condition                        |")
        print("| word = 'hello'                          |")
        print("| char_count = {c: word.count(c) for c in word |")
        print("|              if word.count(c) > 1}      |")
        print("| # {'l': 2}                              |")
        print("|                                         |")
        print("| # Swapping keys and values              |")
        print("| original = {'a': 1, 'b': 2, 'c': 3}     |")
        print("| swapped = {v: k for k, v in original.items()} |")
        print("| # {1: 'a', 2: 'b', 3: 'c'}             |")
        print("+-------------------------------------------+")
        print()
        print("3. SET COMPREHENSIONS:")
        print("+-------------------------------------------+")
        print("| # Basic set comprehension               |")
        print("| squares_set = {x**2 for x in range(-5, 6)} |")
        print("| # {0, 1, 4, 9, 16, 25} (unique values)  |")
        print("|                                         |")
        print("| # Extract unique characters             |")
        print("| text = 'hello world!'                   |")
        print("| unique_chars = {c.lower() for c in text |")
        print("|                if c.isalpha()}          |")
        print("| # {'h', 'e', 'l', 'o', 'w', 'r', 'd'}   |")
        print("|                                         |")
        print("| # Flatten nested structure              |")
        print("| nested_lists = [[1, 2], [3, 4], [5, 6]] |")
        print("| flattened = {item for sublist in nested_lists |")
        print("|             for item in sublist}       |")
        print("| # {1, 2, 3, 4, 5, 6}                   |")
        print("|                                         |")
        print("| # Performance comparison                |")
        print("| # List: [x for x in range(1000000)]     |")
        print("| # Set:  {x for x in range(1000000)}     |")
        print("| # Dict: {x: x**2 for x in range(1000000)} |")
        print("+-------------------------------------------+")

    def show_python_generators(self):
        """Shows Python generators and generator expressions"""
        print("\n" + "=" * 75)
        print(">> PYTHON GENERATORS")
        print("=" * 75)
        print()
        print("Generators are memory-efficient iterators that yield values on demand.")
        print()
        print("1. GENERATOR FUNCTIONS:")
        print("+-------------------------------------------+")
        print("| # Generator function with yield          |")
        print("| def countdown(n):                       |")
        print("|     while n > 0:                        |")
        print("|         yield n                         |")
        print("|         n -= 1                          |")
        print("|     yield 'Blast off!'                  |")
        print("|                                         |")
        print("| # Usage                                 |")
        print("| gen = countdown(3)                      |")
        print("| for value in gen:                       |")
        print("|     print(value)  # 3, 2, 1, Blast off! |")
        print("|                                         |")
        print("| # Fibonacci generator                   |")
        print("| def fibonacci():                        |")
        print("|     a, b = 0, 1                         |")
        print("|     while True:                         |")
        print("|         yield a                         |")
        print("|         a, b = b, a + b                 |")
        print("|                                         |")
        print("| # Get first 10 Fibonacci numbers        |")
        print("| fib = fibonacci()                       |")
        print("| first_10 = [next(fib) for _ in range(10)] |")
        print("+-------------------------------------------+")
        print()
        print("2. GENERATOR EXPRESSIONS:")
        print("+-------------------------------------------+")
        print("| # Generator expression syntax           |")
        print("| squares_gen = (x**2 for x in range(10)) |")
        print("| print(type(squares_gen))  # <generator> |")
        print("|                                         |")
        print("| # Memory efficient - values on demand   |")
        print("| large_gen = (x for x in range(1000000)) |")
        print("| # Uses minimal memory until iterated    |")
        print("|                                         |")
        print("| # Processing large files                |")
        print("| def read_large_file(file_path):         |")
        print("|     with open(file_path, 'r') as f:     |")
        print("|         for line in f:                  |")
        print("|             yield line.strip()          |")
        print("|                                         |")
        print("| # lines = read_large_file('huge.txt')   |")
        print("| # for line in lines:                    |")
        print("| #     process(line)  # Memory efficient |")
        print("+-------------------------------------------+")
        print()
        print("3. ADVANCED GENERATOR FEATURES:")
        print("+-------------------------------------------+")
        print("| # Generator with send() method          |")
        print("| def echo_generator():                   |")
        print("|     while True:                         |")
        print("|         value = yield                   |")
        print("|         if value is not None:           |")
        print("|             yield f'Echo: {value}'      |")
        print("|                                         |")
        print("| gen = echo_generator()                  |")
        print("| next(gen)  # Prime the generator        |")
        print("| result = gen.send('Hello')  # 'Echo: Hello' |")
        print("|                                         |")
        print("| # Generator pipelines                   |")
        print("| def numbers():                          |")
        print("|     for i in range(10):                 |")
        print("|         yield i                         |")
        print("|                                         |")
        print("| def squares(seq):                       |")
        print("|     for num in seq:                     |")
        print("|         yield num ** 2                  |")
        print("|                                         |")
        print("| # Pipeline: numbers -> squares -> filter |")
        print("| result = squares(numbers())             |")
        print("+-------------------------------------------+")

    def show_python_iterators(self):
        """Shows Python iterators and iteration protocol"""
        print("\n" + "=" * 75)
        print(">> PYTHON ITERATORS")
        print("=" * 75)
        print()
        print("Iterators are objects that implement the iteration protocol.")
        print()
        print("1. ITERATION PROTOCOL:")
        print("+-------------------------------------------+")
        print("| # Any object with __iter__ and __next__ |")
        print("| class Counter:                          |")
        print("|     def __init__(self, start, end):     |")
        print("|         self.current = start            |")
        print("|         self.end = end                  |")
        print("|                                         |")
        print("|     def __iter__(self):                 |")
        print("|         return self                     |")
        print("|                                         |")
        print("|     def __next__(self):                 |")
        print("|         if self.current < self.end:     |")
        print("|             current = self.current      |")
        print("|             self.current += 1            |")
        print("|             return current               |")
        print("|         raise StopIteration             |")
        print("|                                         |")
        print("| # Usage                                 |")
        print("| counter = Counter(1, 4)                 |")
        print("| for num in counter:                     |")
        print("|     print(num)  # 1, 2, 3              |")
        print("+-------------------------------------------+")
        print()
        print("2. BUILT-IN ITERATORS:")
        print("+-------------------------------------------+")
        print("| # iter() function creates iterators     |")
        print("| numbers = [1, 2, 3, 4, 5]               |")
        print("| iterator = iter(numbers)                |")
        print("| print(next(iterator))  # 1              |")
        print("| print(next(iterator))  # 2              |")
        print("|                                         |")
        print("| # enumerate() creates index-value pairs |")
        print("| for index, value in enumerate(['a', 'b', 'c']): |")
        print("|     print(f'{index}: {value}')         |")
        print("|                                         |")
        print("| # zip() iterates over multiple sequences |")
        print("| names = ['Alice', 'Bob', 'Charlie']     |")
        print("| ages = [25, 30, 35]                     |")
        print("| for name, age in zip(names, ages):      |")
        print("|     print(f'{name} is {age}')          |")
        print("|                                         |")
        print("| # reversed() iterates in reverse        |")
        print("| for item in reversed([1, 2, 3]):        |")
        print("|     print(item)  # 3, 2, 1             |")
        print("+-------------------------------------------+")
        print()
        print("3. ITERTOOLS MODULE:")
        print("+-------------------------------------------+")
        print("| import itertools                        |")
        print("|                                         |")
        print("| # count() - infinite counter            |")
        print("| counter = itertools.count(10, 2)        |")
        print("| # 10, 12, 14, 16, 18, ... (infinite)   |")
        print("|                                         |")
        print("| # cycle() - infinite repetition         |")
        print("| colors = itertools.cycle(['red', 'green', 'blue']) |")
        print("| # red, green, blue, red, green, blue... |")
        print("|                                         |")
        print("| # chain() - flatten multiple iterables  |")
        print("| numbers = itertools.chain([1, 2], [3, 4], [5, 6]) |")
        print("| list(numbers)  # [1, 2, 3, 4, 5, 6]    |")
        print("|                                         |")
        print("| # combinations() - generate combinations |")
        print("| from itertools import combinations       |")
        print("| combos = combinations('ABC', 2)         |")
        print("| list(combos)  # [('A','B'), ('A','C'), ('B','C')] |")
        print("|                                         |")
        print("| # groupby() - group consecutive elements |")
        print("| from itertools import groupby           |")
        print("| data = [1, 1, 2, 2, 2, 3, 1, 1]         |")
        print("| for key, group in groupby(data):        |")
        print("|     print(key, list(group))            |")
        print("+-------------------------------------------+")

    def show_python_decorators(self):
        """Shows Python decorators for function and class modification"""
        print("\n" + "=" * 75)
        print(">> PYTHON DECORATORS")
        print("=" * 75)
        print()
        print("Decorators modify functions and classes without changing their code.")
        print()
        print("1. BASIC DECORATORS:")
        print("+-------------------------------------------+")
        print("| # Simple decorator function             |")
        print("| def my_decorator(func):                 |")
        print("|     def wrapper():                      |")
        print("|         print('Before function call')   |")
        print("|         result = func()                 |")
        print("|         print('After function call')    |")
        print("|         return result                   |")
        print("|     return wrapper                      |")
        print("|                                         |")
        print("| # Using decorator with @ syntax         |")
        print("| @my_decorator                           |")
        print("| def say_hello():                        |")
        print("|     print('Hello!')                    |")
        print("|                                         |")
        print("| # Equivalent to:                        |")
        print("| # say_hello = my_decorator(say_hello)   |")
        print("|                                         |")
        print("| say_hello()  # Prints all three messages |")
        print("+-------------------------------------------+")
        print()
        print("2. DECORATORS WITH ARGUMENTS:")
        print("+-------------------------------------------+")
        print("| import functools                        |")
        print("|                                         |")
        print("| def timer(func):                        |")
        print("|     @functools.wraps(func)              |")
        print("|     def wrapper(*args, **kwargs):       |")
        print("|         import time                     |")
        print("|         start = time.time()             |")
        print("|         result = func(*args, **kwargs)  |")
        print("|         end = time.time()               |")
        print("|         print(f'{func.__name__} took {end-start:.4f}s') |")
        print("|         return result                   |")
        print("|     return wrapper                      |")
        print("|                                         |")
        print("| @timer                                  |")
        print("| def slow_function(n):                   |")
        print("|     import time                         |")
        print("|     time.sleep(n)                       |")
        print("|     return f'Slept for {n} seconds'     |")
        print("|                                         |")
        print("| result = slow_function(1)  # Times execution |")
        print("+-------------------------------------------+")
        print()
        print("3. DECORATOR FACTORIES:")
        print("+-------------------------------------------+")
        print("| # Decorator that takes parameters       |")
        print("| def repeat(times):                      |")
        print("|     def decorator(func):                |")
        print("|         @functools.wraps(func)          |")
        print("|         def wrapper(*args, **kwargs):   |")
        print("|             for _ in range(times):      |")
        print("|                 result = func(*args, **kwargs) |")
        print("|             return result               |")
        print("|         return wrapper                  |")
        print("|     return decorator                    |")
        print("|                                         |")
        print("| @repeat(3)                              |")
        print("| def greet(name):                        |")
        print("|     print(f'Hello, {name}!')           |")
        print("|                                         |")
        print("| greet('Alice')  # Prints 3 times        |")
        print("|                                         |")
        print("| # Class-based decorators                |")
        print("| class CountCalls:                       |")
        print("|     def __init__(self, func):           |")
        print("|         self.func = func                |")
        print("|         self.count = 0                  |")
        print("|                                         |")
        print("|     def __call__(self, *args, **kwargs): |")
        print("|         self.count += 1                 |")
        print("|         print(f'Call {self.count} to {self.func.__name__}') |")
        print("|         return self.func(*args, **kwargs) |")
        print("+-------------------------------------------+")

    def show_python_error_handling(self):
        """Shows Python error handling with try-except-finally"""
        print("\n" + "=" * 75)
        print(">> PYTHON ERROR HANDLING")
        print("=" * 75)
        print()
        print("Error handling manages exceptions gracefully during program execution.")
        print()
        print("1. BASIC TRY-EXCEPT:")
        print("+-------------------------------------------+")
        print("| # Basic exception handling              |")
        print("| try:                                    |")
        print("|     number = int(input('Enter number: ')) |")
        print("|     result = 10 / number                |")
        print("|     print(f'Result: {result}')          |")
        print("| except ValueError:                      |")
        print("|     print('Invalid input! Please enter a number.') |")
        print("| except ZeroDivisionError:               |")
        print("|     print('Cannot divide by zero!')     |")
        print("|                                         |")
        print("| # Multiple exceptions in one block      |")
        print("| try:                                    |")
        print("|     # risky code                        |")
        print("|     pass                                |")
        print("| except (ValueError, TypeError, KeyError): |")
        print("|     print('One of several errors occurred') |")
        print("+-------------------------------------------+")
        print()
        print("2. ADVANCED EXCEPTION HANDLING:")
        print("+-------------------------------------------+")
        print("| # Catching all exceptions with details  |")
        print("| try:                                    |")
        print("|     # some operation                    |")
        print("|     risky_operation()                   |")
        print("| except Exception as e:                  |")
        print("|     print(f'Error: {type(e).__name__}: {e}') |")
        print("|                                         |")
        print("| # try-except-else-finally               |")
        print("| try:                                    |")
        print("|     file = open('data.txt', 'r')        |")
        print("|     content = file.read()               |")
        print("| except FileNotFoundError:               |")
        print("|     print('File not found!')           |")
        print("| except PermissionError:                 |")
        print("|     print('Permission denied!')        |")
        print("| else:                                   |")
        print("|     print('File read successfully!')   |")
        print("|     process_content(content)            |")
        print("| finally:                                |")
        print("|     if 'file' in locals():              |")
        print("|         file.close()                    |")
        print("|     print('Cleanup completed')         |")
        print("+-------------------------------------------+")
        print()
        print("3. CUSTOM EXCEPTIONS & CONTEXT MANAGERS:")
        print("+-------------------------------------------+")
        print("| # Custom exception classes              |")
        print("| class CustomError(Exception):           |")
        print("|     def __init__(self, message, code):  |")
        print("|         super().__init__(message)       |")
        print("|         self.code = code                |")
        print("|                                         |")
        print("| def validate_age(age):                  |")
        print("|     if age < 0:                         |")
        print("|         raise CustomError('Age cannot be negative', 'AGE_001') |")
        print("|     if age > 150:                       |")
        print("|         raise CustomError('Age too high', 'AGE_002') |")
        print("|                                         |")
        print("| # Context managers (with statement)     |")
        print("| class FileManager:                      |")
        print("|     def __init__(self, filename, mode): |")
        print("|         self.filename = filename        |")
        print("|         self.mode = mode                |")
        print("|                                         |")
        print("|     def __enter__(self):                |")
        print("|         self.file = open(self.filename, self.mode) |")
        print("|         return self.file                |")
        print("|                                         |")
        print("|     def __exit__(self, exc_type, exc_val, exc_tb): |")
        print("|         self.file.close()               |")
        print("|                                         |")
        print("| # Usage                                 |")
        print("| with FileManager('data.txt', 'r') as f: |")
        print("|     content = f.read()                  |")
        print("| # File automatically closed             |")
        print("+-------------------------------------------+")

    def show_python_modules(self):
        """Shows Python modules and packages for code organization"""
        print("\n" + "=" * 75)
        print(">> PYTHON MODULES & PACKAGES")
        print("=" * 75)
        print()
        print("Modules and packages organize code into reusable components.")
        print()
        print("1. CREATING AND IMPORTING MODULES:")
        print("+-------------------------------------------+")
        print("| # File: my_module.py                    |")
        print("| def greet(name):                        |")
        print("|     return f'Hello, {name}!'           |")
        print("|                                         |")
        print("| def add(a, b):                          |")
        print("|     return a + b                        |")
        print("|                                         |")
        print("| PI = 3.14159                            |")
        print("|                                         |")
        print("| # File: main.py                         |")
        print("| # Different import methods              |")
        print("|                                         |")
        print("| # 1. Import entire module               |")
        print("| import my_module                        |")
        print("| print(my_module.greet('Alice'))         |")
        print("| print(my_module.PI)                     |")
        print("|                                         |")
        print("| # 2. Import specific functions          |")
        print("| from my_module import greet, add        |")
        print("| print(greet('Bob'))                     |")
        print("| result = add(5, 3)                      |")
        print("|                                         |")
        print("| # 3. Import with alias                  |")
        print("| import my_module as mm                  |")
        print("| print(mm.greet('Charlie'))              |")
        print("+-------------------------------------------+")
        print()
        print("2. PACKAGES (DIRECTORIES WITH __init__.py):")
        print("+-------------------------------------------+")
        print("| # Directory structure:                  |")
        print("| my_package/                             |")
        print("|     __init__.py                         |")
        print("|     math_utils.py                       |")
        print("|     string_utils.py                     |")
        print("|     sub_package/                        |")
        print("|         __init__.py                     |")
        print("|         advanced.py                     |")
        print("|                                         |")
        print("| # File: my_package/__init__.py          |")
        print("| __version__ = '1.0.0'                   |")
        print("| __author__ = 'Your Name'                |")
        print("|                                         |")
        print("| # Make functions available at package level |")
        print("| from .math_utils import calculator      |")
        print("| from .string_utils import formatter     |")
        print("|                                         |")
        print("| # File: my_package/math_utils.py        |")
        print("| def calculator(operation, a, b):        |")
        print("|     if operation == 'add':              |")
        print("|         return a + b                    |")
        print("|     elif operation == 'multiply':       |")
        print("|         return a * b                    |")
        print("|     return None                         |")
        print("+-------------------------------------------+")
        print()
        print("3. MODULE SEARCH PATH & IMPORT MECHANISMS:")
        print("+-------------------------------------------+")
        print("| import sys                              |")
        print("| import os                               |")
        print("|                                         |")
        print("| # Check module search path              |")
        print("| print(sys.path)                         |")
        print("|                                         |")
        print("| # Add custom path                       |")
        print("| sys.path.append('/path/to/my/modules')  |")
        print("|                                         |")
        print("| # Dynamic imports                       |")
        print("| import importlib                        |")
        print("| module_name = 'math'                    |")
        print("| math_module = importlib.import_module(module_name) |")
        print("| print(math_module.pi)  # 3.141592653589793 |")
        print("|                                         |")
        print("| # Reload module (useful in development) |")
        print("| import my_module                        |")
        print("| importlib.reload(my_module)             |")
        print("|                                         |")
        print("| # Module introspection                  |")
        print("| import inspect                          |")
        print("| print(inspect.getfile(my_module))       |")
        print("| print(dir(my_module))  # List all attributes |")
        print("|                                         |")
        print("| # Conditional imports                   |")
        print("| try:                                    |")
        print("|     import numpy as np                  |")
        print("|     HAS_NUMPY = True                    |")
        print("| except ImportError:                     |")
        print("|     HAS_NUMPY = False                   |")
        print("|                                         |")
        print("| if HAS_NUMPY:                           |")
        print("|     # use numpy features                |")
        print("|     arr = np.array([1, 2, 3])           |")
        print("+-------------------------------------------+")