"""
Java Fundamentals - Basic Java programming concepts and syntax
"""


class JavaFundamentals:
    def __init__(self):
        pass

    def show_java_intro(self):
        """Displays Java introduction and concepts"""
        print("\n" + "=" * 70)
        print(">> JAVA INTRO AND CONCEPTS")
        print("=" * 70)
        print()
        print("Java is a high-level, object-oriented programming language.")
        print()
        print("Key Features:")
        print("* Platform Independent (Write Once, Run Anywhere)")
        print("* Object-Oriented Programming (OOP)")
        print("* Robust and Secure")
        print("* Multithreaded")
        print("* High Performance")
        print("* Dynamic and Extensible")
        print()
        print("Java Architecture:")
        print("Source Code (.java) → Bytecode (.class) → JVM → Machine Code")
        print()
        print("Basic Java Program Structure:")
        print("+-------------------------------------------+")
        print("| public class HelloWorld {               |")
        print("|     public static void main(String[] args) { |")
        print("|         System.out.println(\"Hello World!\"); |")
        print("|     }                                    |")
        print("| }                                        |")
        print("+-------------------------------------------+")

    def show_java_syntax(self):
        """Displays Java syntax rules and structure"""
        print("\n" + "=" * 70)
        print(">> JAVA SYNTAX")
        print("=" * 70)
        print()
        print("Java syntax defines the rules for writing Java programs.")
        print()
        print("Basic Program Structure:")
        print("+-------------------------------------------+")
        print("| package com.example;                    |")
        print("| import java.util.*;                     |")
        print("|                                         |")
        print("| public class MyClass {                  |")
        print("|     public static void main(String[] args) { |")
        print("|         // Your code here               |")
        print("|     }                                   |")
        print("| }                                       |")
        print("+-------------------------------------------+")
        print()
        print("Key Syntax Rules:")
        print("* Case-sensitive language")
        print("* Statements end with semicolon (;)")
        print("* Code blocks use curly braces { }")
        print("* Class names start with uppercase")
        print("* Method/variable names start with lowercase")

    def show_java_output(self):
        """Displays Java output and print statements"""
        print("\n" + "=" * 70)
        print(">> JAVA OUTPUT & PRINT STATEMENTS")
        print("=" * 70)
        print()
        print("Java provides several ways to display output:")
        print()
        print("1. System.out.println() - Prints with newline")
        print("   System.out.println(\"Hello World!\");")
        print()
        print("2. System.out.print() - Prints without newline")
        print("   System.out.print(\"Hello \");")
        print("   System.out.print(\"World!\");")
        print()
        print("3. System.out.printf() - Formatted output")
        print("   System.out.printf(\"Name: %s, Age: %d%n\", \"John\", 25);")
        print()
        print("Examples:")
        print("+-------------------------------------------+")
        print("| System.out.println(\"Text\");             |")
        print("| System.out.println(42);                 |")
        print("| System.out.println(3.14);               |")
        print("| System.out.printf(\"%.2f%n\", 3.14159);   |")
        print("+-------------------------------------------+")

    def show_java_comments(self):
        """Displays Java comments and documentation"""
        print("\n" + "=" * 70)
        print(">> JAVA COMMENTS & DOCUMENTATION")
        print("=" * 70)
        print()
        print("Comments help document your code:")
        print()
        print("1. Single-line comments:")
        print("   // This is a single-line comment")
        print()
        print("2. Multi-line comments:")
        print("   /* This is a")
        print("      multi-line comment */")
        print()
        print("3. Javadoc comments:")
        print("   /**")
        print("    * This method calculates area")
        print("    * @param radius The circle radius")
        print("    * @return The calculated area")
        print("    */")
        print()
        print("Best Practices:")
        print("* Use comments to explain WHY, not WHAT")
        print("* Keep comments updated with code changes")
        print("* Use meaningful variable names to reduce comment needs")

    def show_java_variables(self):
        """Displays Java variables and naming conventions"""
        print("\n" + "=" * 70)
        print(">> JAVA VARIABLES & NAMING")
        print("=" * 70)
        print()
        print("Variables store data values:")
        print()
        print("Declaration and Assignment:")
        print("  int age;              // Declaration")
        print("  age = 25;             // Assignment")
        print("  int count = 0;        // Declaration + Assignment")
        print()
        print("Variable Types:")
        print("* Local variables - Inside methods")
        print("* Instance variables - Inside class, outside methods")
        print("* Class/Static variables - With static keyword")
        print()
        print("Naming Rules:")
        print("* Must start with letter, $, or _")
        print("* Cannot start with digit")
        print("* Case-sensitive")
        print("* Cannot use Java keywords")
        print()
        print("Naming Conventions:")
        print("* camelCase for variables/methods")
        print("* PascalCase for classes")
        print("* UPPER_CASE for constants")

    def show_java_data_types(self):
        """Displays Java data types and primitives"""
        print("\n" + "=" * 70)
        print(">> JAVA DATA TYPES & PRIMITIVES")
        print("=" * 70)
        print()
        print("Java has 8 primitive data types:")
        print()
        print("Integer Types:")
        print("  byte    -  8 bits  (-128 to 127)")
        print("  short   - 16 bits  (-32,768 to 32,767)")
        print("  int     - 32 bits  (-2^31 to 2^31-1)")
        print("  long    - 64 bits  (-2^63 to 2^63-1)")
        print()
        print("Floating-Point Types:")
        print("  float   - 32 bits  (6-7 decimal digits)")
        print("  double  - 64 bits  (15-16 decimal digits)")
        print()
        print("Other Types:")
        print("  boolean - true or false")
        print("  char    - 16 bits Unicode character")
        print()
        print("Examples:")
        print("  int age = 25;")
        print("  double price = 19.99;")
        print("  boolean isActive = true;")
        print("  char grade = 'A';")

    def show_java_type_casting(self):
        """Displays Java type casting and conversion"""
        print("\n" + "=" * 70)
        print(">> JAVA TYPE CASTING & CONVERSION")
        print("=" * 70)
        print()
        print("Type casting converts one data type to another:")
        print()
        print("1. Implicit Casting (Automatic):")
        print("   byte → short → int → long → float → double")
        print()
        print("   int myInt = 9;")
        print("   double myDouble = myInt;  // Automatic casting")
        print()
        print("2. Explicit Casting (Manual):")
        print("   double → float → long → int → short → byte")
        print()
        print("   double myDouble = 9.78;")
        print("   int myInt = (int) myDouble;  // Manual casting")
        print()
        print("Examples:")
        print("+-------------------------------------------+")
        print("| int x = 10;                             |")
        print("| double y = x;        // 10.0            |")
        print("| int z = (int) 9.99;  // 9               |")
        print("+-------------------------------------------+")

    def show_java_operators(self):
        """Displays Java operators and expressions"""
        print("\n" + "=" * 70)
        print(">> JAVA OPERATORS & EXPRESSIONS")
        print("=" * 70)
        print()
        print("Java operators perform operations on variables and values:")
        print()
        print("Arithmetic Operators:")
        print("  +  Addition       int sum = 5 + 3;      // 8")
        print("  -  Subtraction    int diff = 5 - 3;     // 2")
        print("  *  Multiplication int prod = 5 * 3;     // 15")
        print("  /  Division       int quot = 6 / 3;     // 2")
        print("  %  Modulus        int rem = 7 % 3;      // 1")
        print()
        print("Assignment Operators:")
        print("  =   x = 5      +=  x += 3  (x = x + 3)")
        print("  -=  x -= 3     *=  x *= 2  /=  x /= 2")
        print()
        print("Comparison Operators:")
        print("  ==  Equal to      !=  Not equal")
        print("  >   Greater than  <   Less than")
        print("  >=  Greater/equal <=  Less/equal")
        print()
        print("Logical Operators:")
        print("  &&  Logical AND   ||  Logical OR")
        print("  !   Logical NOT")