package com.prolanlab.tutorials.python.datastructures;

import com.prolanlab.Main;
import java.util.Scanner;

/**
 * PythonDataStructures - Data structures tutorial for Python
 * Contains methods extracted from PythonTutorial.java (methods 52-60)
 */
public class PythonDataStructures {
    
    /**
     * Shows Python Lists and Arrays implementation and usage
     */
    public void showPythonListsArrays() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> LISTS AND ARRAYS");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Lists and arrays are fundamental data structures for storing collections.");
        System.out.println();
        System.out.println("1. PYTHON LISTS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Dynamic arrays in Python              |");
        System.out.println("| numbers = [1, 2, 3, 4, 5]              |");
        System.out.println("| mixed = ['hello', 42, 3.14, True]       |");
        System.out.println("|                                         |");
        System.out.println("| # List operations                       |");
        System.out.println("| numbers.append(6)       # Add to end    |");
        System.out.println("| numbers.insert(0, 0)    # Insert at index |");
        System.out.println("| numbers.remove(3)       # Remove first 3 |");
        System.out.println("| last = numbers.pop()    # Remove last   |");
        System.out.println("|                                         |");
        System.out.println("| # List comprehensions                   |");
        System.out.println("| squares = [x**2 for x in range(10)]     |");
        System.out.println("| evens = [x for x in numbers if x % 2 == 0] |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. NUMPY ARRAYS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| import numpy as np                      |");
        System.out.println("|                                         |");
        System.out.println("| # Creating arrays                       |");
        System.out.println("| arr = np.array([1, 2, 3, 4, 5])         |");
        System.out.println("| zeros = np.zeros(5)     # [0. 0. 0. 0. 0.] |");
        System.out.println("| ones = np.ones(3)       # [1. 1. 1.]    |");
        System.out.println("| range_arr = np.arange(0, 10, 2)  # [0 2 4 6 8] |");
        System.out.println("|                                         |");
        System.out.println("| # Array operations (vectorized)         |");
        System.out.println("| arr2 = arr * 2          # [2 4 6 8 10]  |");
        System.out.println("| arr3 = arr + arr2       # [3 6 9 12 15] |");
        System.out.println("| mean_val = np.mean(arr) # 3.0           |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. MULTIDIMENSIONAL ARRAYS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # 2D arrays (matrices)                  |");
        System.out.println("| matrix = np.array([[1, 2, 3],           |");
        System.out.println("|                    [4, 5, 6],           |");
        System.out.println("|                    [7, 8, 9]])          |");
        System.out.println("|                                         |");
        System.out.println("| # Array properties                      |");
        System.out.println("| print(matrix.shape)     # (3, 3)       |");
        System.out.println("| print(matrix.size)      # 9            |");
        System.out.println("| print(matrix.dtype)     # int64         |");
        System.out.println("|                                         |");
        System.out.println("| # Indexing and slicing                  |");
        System.out.println("| print(matrix[0, 1])     # 2 (row 0, col 1) |");
        System.out.println("| print(matrix[:, 1])     # [2 5 8] (col 1) |");
        System.out.println("| print(matrix[1, :])     # [4 5 6] (row 1) |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Stack implementation using list-based approach
     */
    public void showPythonStacks() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON STACKS");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Stacks follow Last-In-First-Out (LIFO) principle.");
        System.out.println();
        System.out.println("1. STACK USING LISTS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Stack:                            |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.items = []                 |");
        System.out.println("|                                         |");
        System.out.println("|     def push(self, item):               |");
        System.out.println("|         self.items.append(item)         |");
        System.out.println("|                                         |");
        System.out.println("|     def pop(self):                      |");
        System.out.println("|         if not self.is_empty():         |");
        System.out.println("|             return self.items.pop()     |");
        System.out.println("|         raise IndexError('Stack is empty') |");
        System.out.println("|                                         |");
        System.out.println("|     def peek(self):                     |");
        System.out.println("|         if not self.is_empty():         |");
        System.out.println("|             return self.items[-1]       |");
        System.out.println("|         return None                     |");
        System.out.println("|                                         |");
        System.out.println("|     def is_empty(self):                 |");
        System.out.println("|         return len(self.items) == 0     |");
        System.out.println("|                                         |");
        System.out.println("|     def size(self):                     |");
        System.out.println("|         return len(self.items)          |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. STACK OPERATIONS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| stack = Stack()                         |");
        System.out.println("|                                         |");
        System.out.println("| # Push elements                         |");
        System.out.println("| stack.push(10)                         |");
        System.out.println("| stack.push(20)                         |");
        System.out.println("| stack.push(30)                         |");
        System.out.println("|                                         |");
        System.out.println("| # Stack state: [10, 20, 30] (top=30)    |");
        System.out.println("{ print(f'Size: {stack.size()}')  # 3     |");
        System.out.println("| print(f'Top: {stack.peek()}')   # 30   |");
        System.out.println("|                                         |");
        System.out.println("| # Pop elements                          |");
        System.out.println("| item = stack.pop()  # 30               |");
        System.out.println("| print(f'Popped: {item}')               |");
        System.out.println("| print(f'New top: {stack.peek()}')  # 20 |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. PRACTICAL APPLICATIONS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Function call stack                   |");
        System.out.println("| def factorial(n):                       |");
        System.out.println("|     if n <= 1:                         |");
        System.out.println("|         return 1                        |");
        System.out.println("|     return n * factorial(n - 1)         |");
        System.out.println("|                                         |");
        System.out.println("| # Balanced parentheses checker          |");
        System.out.println("| def is_balanced(expression):            |");
        System.out.println("|     stack = Stack()                     |");
        System.out.println("|     for char in expression:             |");
        System.out.println("|         if char in '({[':               |");
        System.out.println("|             stack.push(char)            |");
        System.out.println("|         elif char in ')}]':             |");
        System.out.println("|             if stack.is_empty():        |");
        System.out.println("|                 return False            |");
        System.out.println("|             stack.pop()                 |");
        System.out.println("|     return stack.is_empty()             |");
        System.out.println("|                                         |");
        System.out.println("| print(is_balanced('()[]{}'))  # True    |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Queue implementations including circular and priority queues
     */
    public void showPythonQueues() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON QUEUES");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Queues follow First-In-First-Out (FIFO) principle.");
        System.out.println();
        System.out.println("1. QUEUE USING COLLECTIONS.DEQUE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| from collections import deque           |");
        System.out.println("|                                         |");
        System.out.println("| class Queue:                            |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.items = deque()            |");
        System.out.println("|                                         |");
        System.out.println("|     def enqueue(self, item):            |");
        System.out.println("|         self.items.append(item)         |");
        System.out.println("|                                         |");
        System.out.println("|     def dequeue(self):                  |");
        System.out.println("|         if not self.is_empty():         |");
        System.out.println("|             return self.items.popleft() |");
        System.out.println("|         raise IndexError('Queue is empty') |");
        System.out.println("|                                         |");
        System.out.println("|     def front(self):                    |");
        System.out.println("|         if not self.is_empty():         |");
        System.out.println("|             return self.items[0]        |");
        System.out.println("|         return None                     |");
        System.out.println("|                                         |");
        System.out.println("|     def is_empty(self):                 |");
        System.out.println("|         return len(self.items) == 0     |");
        System.out.println("|                                         |");
        System.out.println("|     def size(self):                     |");
        System.out.println("|         return len(self.items)          |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. PRIORITY QUEUE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| import heapq                            |");
        System.out.println("|                                         |");
        System.out.println("| class PriorityQueue:                    |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.heap = []                  |");
        System.out.println("|         self.index = 0                  |");
        System.out.println("|                                         |");
        System.out.println("|     def put(self, item, priority):      |");
        System.out.println("|         heapq.heappush(self.heap, (priority, self.index, item)) |");
        System.out.println("|         self.index += 1                 |");
        System.out.println("|                                         |");
        System.out.println("|     def get(self):                      |");
        System.out.println("|         if self.heap:                   |");
        System.out.println("|             return heapq.heappop(self.heap)[2] |");
        System.out.println("|         raise IndexError('Queue is empty') |");
        System.out.println("|                                         |");
        System.out.println("| # Usage                                 |");
        System.out.println("| pq = PriorityQueue()                    |");
        System.out.println("| pq.put('Task 1', 3)  # Lower = higher priority |");
        System.out.println("| pq.put('Task 2', 1)                    |");
        System.out.println("| pq.put('Task 3', 2)                    |");
        System.out.println("| print(pq.get())  # 'Task 2' (priority 1) |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. CIRCULAR QUEUE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class CircularQueue:                    |");
        System.out.println("|     def __init__(self, size):           |");
        System.out.println("|         self.size = size                |");
        System.out.println("|         self.queue = [None] * size      |");
        System.out.println("|         self.front = 0                  |");
        System.out.println("|         self.rear = 0                   |");
        System.out.println("|         self.count = 0                  |");
        System.out.println("|                                         |");
        System.out.println("|     def enqueue(self, item):            |");
        System.out.println("|         if self.count == self.size:     |");
        System.out.println("|             raise OverflowError('Queue full') |");
        System.out.println("|         self.queue[self.rear] = item    |");
        System.out.println("|         self.rear = (self.rear + 1) % self.size |");
        System.out.println("|         self.count += 1                 |");
        System.out.println("|                                         |");
        System.out.println("|     def dequeue(self):                  |");
        System.out.println("|         if self.count == 0:             |");
        System.out.println("|             raise IndexError('Queue empty') |");
        System.out.println("|         item = self.queue[self.front]   |");
        System.out.println("|         self.front = (self.front + 1) % self.size |");
        System.out.println("|         self.count -= 1                 |");
        System.out.println("|         return item                     |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Linked List implementations including singly and doubly linked lists
     */
    public void showPythonLinkedLists() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> LINKED LISTS");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Linked lists store data in nodes connected by pointers.");
        System.out.println();
        System.out.println("1. SINGLY LINKED LIST:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class ListNode:                         |");
        System.out.println("|     def __init__(self, data):           |");
        System.out.println("|         self.data = data                |");
        System.out.println("|         self.next = None                |");
        System.out.println("|                                         |");
        System.out.println("| class LinkedList:                       |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.head = None                |");
        System.out.println("|                                         |");
        System.out.println("|     def append(self, data):             |");
        System.out.println("|         new_node = ListNode(data)       |");
        System.out.println("|         if not self.head:               |");
        System.out.println("|             self.head = new_node        |");
        System.out.println("|         else:                           |");
        System.out.println("|             current = self.head         |");
        System.out.println("|             while current.next:         |");
        System.out.println("|                 current = current.next  |");
        System.out.println("|             current.next = new_node     |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. LINKED LIST OPERATIONS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("|     def prepend(self, data):            |");
        System.out.println("|         new_node = ListNode(data)       |");
        System.out.println("|         new_node.next = self.head       |");
        System.out.println("|         self.head = new_node            |");
        System.out.println("|                                         |");
        System.out.println("|     def delete(self, data):             |");
        System.out.println("|         if not self.head:               |");
        System.out.println("|             return                      |");
        System.out.println("|         if self.head.data == data:      |");
        System.out.println("|             self.head = self.head.next  |");
        System.out.println("|             return                      |");
        System.out.println("|         current = self.head             |");
        System.out.println("|         while current.next:             |");
        System.out.println("|             if current.next.data == data: |");
        System.out.println("|                 current.next = current.next.next |");
        System.out.println("|                 return                  |");
        System.out.println("|             current = current.next      |");
        System.out.println("|                                         |");
        System.out.println("|     def display(self):                  |");
        System.out.println("|         current = self.head             |");
        System.out.println("|         while current:                  |");
        System.out.println("|             print(current.data, end=' -> ') |");
        System.out.println("|             current = current.next      |");
        System.out.println("|         print('None')                   |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. DOUBLY LINKED LIST:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class DoublyNode:                       |");
        System.out.println("|     def __init__(self, data):           |");
        System.out.println("|         self.data = data                |");
        System.out.println("|         self.next = None                |");
        System.out.println("|         self.prev = None                |");
        System.out.println("|                                         |");
        System.out.println("| class DoublyLinkedList:                 |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.head = None                |");
        System.out.println("|         self.tail = None                |");
        System.out.println("|                                         |");
        System.out.println("|     def append(self, data):             |");
        System.out.println("|         new_node = DoublyNode(data)     |");
        System.out.println("|         if not self.head:               |");
        System.out.println("|             self.head = self.tail = new_node |");
        System.out.println("|         else:                           |");
        System.out.println("|             new_node.prev = self.tail   |");
        System.out.println("|             self.tail.next = new_node   |");
        System.out.println("|             self.tail = new_node        |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Hash Table implementation with collision handling techniques
     */
    public void showPythonHashTables() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> HASH TABLES");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Hash tables provide fast key-value lookups using hashing.");
        System.out.println();
        System.out.println("1. PYTHON DICTIONARIES (HASH TABLES):");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Built-in hash table implementation    |");
        System.out.println("| phone_book = {                          |");
        System.out.println("|     'Alice': '555-1234',                |");
        System.out.println("|     'Bob': '555-5678',                  |");
        System.out.println("|     'Charlie': '555-9012'               |");
        System.out.println("| }                                       |");
        System.out.println("|                                         |");
        System.out.println("| # O(1) average time complexity          |");
        System.out.println("| print(phone_book['Alice'])  # '555-1234' |");
        System.out.println("| phone_book['David'] = '555-3456'        |");
        System.out.println("| del phone_book['Bob']                   |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. CUSTOM HASH TABLE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class HashTable:                        |");
        System.out.println("|     def __init__(self, size=10):        |");
        System.out.println("|         self.size = size                |");
        System.out.println("|         self.table = [[] for _ in range(size)] |");
        System.out.println("|                                         |");
        System.out.println("|     def _hash(self, key):               |");
        System.out.println("|         return hash(key) % self.size    |");
        System.out.println("|                                         |");
        System.out.println("|     def put(self, key, value):          |");
        System.out.println("|         hash_key = self._hash(key)      |");
        System.out.println("|         bucket = self.table[hash_key]   |");
        System.out.println("|         for i, (k, v) in enumerate(bucket): |");
        System.out.println("|             if k == key:                |");
        System.out.println("|                 bucket[i] = (key, value) |");
        System.out.println("|                 return                  |");
        System.out.println("|         bucket.append((key, value))    |");
        System.out.println("|                                         |");
        System.out.println("|     def get(self, key):                 |");
        System.out.println("|         hash_key = self._hash(key)      |");
        System.out.println("|         bucket = self.table[hash_key]   |");
        System.out.println("|         for k, v in bucket:             |");
        System.out.println("|             if k == key:                |");
        System.out.println("|                 return v                |");
        System.out.println("|         raise KeyError(key)             |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. COLLISION HANDLING:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Chaining (used above)                 |");
        System.out.println("| # Multiple items in same bucket         |");
        System.out.println("|                                         |");
        System.out.println("| # Open Addressing (Linear Probing)      |");
        System.out.println("| class LinearProbingHashTable:           |");
        System.out.println("|     def __init__(self, size=10):        |");
        System.out.println("|         self.size = size                |");
        System.out.println("|         self.keys = [None] * size       |");
        System.out.println("|         self.values = [None] * size     |");
        System.out.println("|                                         |");
        System.out.println("|     def put(self, key, value):          |");
        System.out.println("|         index = hash(key) % self.size   |");
        System.out.println("|         while self.keys[index] is not None: |");
        System.out.println("|             if self.keys[index] == key:  |");
        System.out.println("|                 self.values[index] = value |");
        System.out.println("|                 return                  |");
        System.out.println("|             index = (index + 1) % self.size |");
        System.out.println("|         self.keys[index] = key          |");
        System.out.println("|         self.values[index] = value      |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Tree data structure with traversal and search algorithms
     */
    public void showPythonTrees() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON TREES");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Trees are hierarchical data structures with nodes and edges.");
        System.out.println();
        System.out.println("1. TREE NODE CLASS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class TreeNode:                         |");
        System.out.println("|     def __init__(self, data):           |");
        System.out.println("|         self.data = data                |");
        System.out.println("|         self.children = []              |");
        System.out.println("|         self.parent = None              |");
        System.out.println("|                                         |");
        System.out.println("|     def add_child(self, child):         |");
        System.out.println("|         child.parent = self             |");
        System.out.println("|         self.children.append(child)     |");
        System.out.println("|                                         |");
        System.out.println("|     def get_level(self):                |");
        System.out.println("|         level = 0                       |");
        System.out.println("|         p = self.parent                 |");
        System.out.println("|         while p:                        |");
        System.out.println("|             level += 1                  |");
        System.out.println("|             p = p.parent                |");
        System.out.println("|         return level                    |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. TREE TRAVERSAL:");
        System.out.println("+-------------------------------------------+");
        System.out.println("|     def print_tree(self):               |");
        System.out.println("|         spaces = ' ' * self.get_level() * 3 |");
        System.out.println("|         prefix = spaces + '|__' if self.parent else '' |");
        System.out.println("|         print(prefix + self.data)       |");
        System.out.println("|         for child in self.children:     |");
        System.out.println("|             child.print_tree()          |");
        System.out.println("|                                         |");
        System.out.println("| # Example: Family Tree                  |");
        System.out.println("| root = TreeNode('Grandparent')          |");
        System.out.println("| parent1 = TreeNode('Parent 1')          |");
        System.out.println("| parent2 = TreeNode('Parent 2')          |");
        System.out.println("| child1 = TreeNode('Child 1')            |");
        System.out.println("| child2 = TreeNode('Child 2')            |");
        System.out.println("|                                         |");
        System.out.println("| root.add_child(parent1)                 |");
        System.out.println("| root.add_child(parent2)                 |");
        System.out.println("| parent1.add_child(child1)               |");
        System.out.println("| parent1.add_child(child2)               |");
        System.out.println("|                                         |");
        System.out.println("| root.print_tree()  # Display hierarchy  |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. TREE SEARCH:");
        System.out.println("+-------------------------------------------+");
        System.out.println("|     def find_node(self, name):          |");
        System.out.println("|         if self.data == name:           |");
        System.out.println("|             return self                 |");
        System.out.println("|         for child in self.children:     |");
        System.out.println("|             result = child.find_node(name) |");
        System.out.println("|             if result:                  |");
        System.out.println("|                 return result           |");
        System.out.println("|         return None                     |");
        System.out.println("|                                         |");
        System.out.println("|     def get_path_to_root(self):         |");
        System.out.println("|         path = []                       |");
        System.out.println("|         current = self                  |");
        System.out.println("|         while current:                  |");
        System.out.println("|             path.append(current.data)   |");
        System.out.println("|             current = current.parent    |");
        System.out.println("|         return ' <- '.join(reversed(path)) |");
        System.out.println("|                                         |");
        System.out.println("| # Usage                                 |");
        System.out.println("| node = root.find_node('Child 1')        |");
        System.out.println("| print(node.get_path_to_root())          |");
        System.out.println("| # Output: 'Grandparent <- Parent 1 <- Child 1' |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Binary Tree implementation with various traversal methods and BST operations
     */
    public void showPythonBinaryTrees() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> BINARY TREES");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Binary trees have at most two children per node (left and right).");
        System.out.println();
        System.out.println("1. BINARY TREE NODE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class BinaryTreeNode:                   |");
        System.out.println("|     def __init__(self, data):           |");
        System.out.println("|         self.data = data                |");
        System.out.println("|         self.left = None                |");
        System.out.println("|         self.right = None               |");
        System.out.println("|                                         |");
        System.out.println("| class BinaryTree:                       |");
        System.out.println("|     def __init__(self, root_data):      |");
        System.out.println("|         self.root = BinaryTreeNode(root_data) |");
        System.out.println("|                                         |");
        System.out.println("|     def add_left_child(self, parent, data): |");
        System.out.println("|         parent.left = BinaryTreeNode(data) |");
        System.out.println("|                                         |");
        System.out.println("|     def add_right_child(self, parent, data): |");
        System.out.println("|         parent.right = BinaryTreeNode(data) |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. TREE TRAVERSALS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("|     # In-order: Left -> Root -> Right   |");
        System.out.println("|     def inorder_traversal(self, node):  |");
        System.out.println("|         if node:                        |");
        System.out.println("|             self.inorder_traversal(node.left) |");
        System.out.println("|             print(node.data, end=' ')   |");
        System.out.println("|             self.inorder_traversal(node.right) |");
        System.out.println("|                                         |");
        System.out.println("|     # Pre-order: Root -> Left -> Right  |");
        System.out.println("|     def preorder_traversal(self, node): |");
        System.out.println("|         if node:                        |");
        System.out.println("|             print(node.data, end=' ')   |");
        System.out.println("|             self.preorder_traversal(node.left) |");
        System.out.println("|             self.preorder_traversal(node.right) |");
        System.out.println("|                                         |");
        System.out.println("|     # Post-order: Left -> Right -> Root |");
        System.out.println("|     def postorder_traversal(self, node): |");
        System.out.println("|         if node:                        |");
        System.out.println("|             self.postorder_traversal(node.left) |");
        System.out.println("|             self.postorder_traversal(node.right) |");
        System.out.println("|             print(node.data, end=' ')   |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. BINARY SEARCH TREE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class BST:                              |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.root = None                |");
        System.out.println("|                                         |");
        System.out.println("|     def insert(self, data):             |");
        System.out.println("|         if not self.root:               |");
        System.out.println("|             self.root = BinaryTreeNode(data) |");
        System.out.println("|         else:                           |");
        System.out.println("|             self._insert_recursive(self.root, data) |");
        System.out.println("|                                         |");
        System.out.println("|     def _insert_recursive(self, node, data): |");
        System.out.println("|         if data < node.data:            |");
        System.out.println("|             if node.left is None:       |");
        System.out.println("|                 node.left = BinaryTreeNode(data) |");
        System.out.println("|             else:                       |");
        System.out.println("|                 self._insert_recursive(node.left, data) |");
        System.out.println("|         else:                           |");
        System.out.println("|             if node.right is None:      |");
        System.out.println("|                 node.right = BinaryTreeNode(data) |");
        System.out.println("|             else:                       |");
        System.out.println("|                 self._insert_recursive(node.right, data) |");
        System.out.println("|                                         |");
        System.out.println("|     def search(self, data):             |");
        System.out.println("|         return self._search_recursive(self.root, data) |");
        System.out.println("|                                         |");
        System.out.println("|     def _search_recursive(self, node, data): |");
        System.out.println("|         if not node or node.data == data: |");
        System.out.println("|             return node                 |");
        System.out.println("|         if data < node.data:            |");
        System.out.println("|             return self._search_recursive(node.left, data) |");
        System.out.println("|         return self._search_recursive(node.right, data) |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Graph data structure implementation with BFS and DFS algorithms
     */
    public void showPythonGraphs() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON GRAPHS");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Graphs consist of vertices (nodes) connected by edges.");
        System.out.println();
        System.out.println("1. ADJACENCY LIST REPRESENTATION:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Graph:                            |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.graph = {}                 |");
        System.out.println("|                                         |");
        System.out.println("|     def add_vertex(self, vertex):       |");
        System.out.println("|         if vertex not in self.graph:    |");
        System.out.println("|             self.graph[vertex] = []     |");
        System.out.println("|                                         |");
        System.out.println("|     def add_edge(self, vertex1, vertex2): |");
        System.out.println("|         self.add_vertex(vertex1)        |");
        System.out.println("|         self.add_vertex(vertex2)        |");
        System.out.println("|         self.graph[vertex1].append(vertex2) |");
        System.out.println("|         self.graph[vertex2].append(vertex1) # Undirected |");
        System.out.println("|                                         |");
        System.out.println("|     def get_vertices(self):             |");
        System.out.println("|         return list(self.graph.keys())  |");
        System.out.println("|                                         |");
        System.out.println("|     def get_edges(self):                |");
        System.out.println("|         edges = []                      |");
        System.out.println("|         for vertex in self.graph:       |");
        System.out.println("|             for neighbor in self.graph[vertex]: |");
        System.out.println("|                 edges.append((vertex, neighbor)) |");
        System.out.println("|         return edges                    |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. GRAPH TRAVERSAL:");
        System.out.println("+-------------------------------------------+");
        System.out.println("|     # Breadth-First Search (BFS)        |");
        System.out.println("|     def bfs(self, start):               |");
        System.out.println("|         visited = set()                 |");
        System.out.println("|         queue = [start]                 |");
        System.out.println("|         result = []                     |");
        System.out.println("|         while queue:                    |");
        System.out.println("|             vertex = queue.pop(0)       |");
        System.out.println("|             if vertex not in visited:   |");
        System.out.println("|                 visited.add(vertex)     |");
        System.out.println("|                 result.append(vertex)   |");
        System.out.println("|                 for neighbor in self.graph[vertex]: |");
        System.out.println("|                     if neighbor not in visited: |");
        System.out.println("|                         queue.append(neighbor) |");
        System.out.println("|         return result                   |");
        System.out.println("|                                         |");
        System.out.println("|     # Depth-First Search (DFS)          |");
        System.out.println("|     def dfs(self, start, visited=None): |");
        System.out.println("|         if visited is None:             |");
        System.out.println("|             visited = set()             |");
        System.out.println("|         visited.add(start)              |");
        System.out.println("|         result = [start]                |");
        System.out.println("|         for neighbor in self.graph[start]: |");
        System.out.println("|             if neighbor not in visited: |");
        System.out.println("|                 result.extend(self.dfs(neighbor, visited)) |");
        System.out.println("|         return result                   |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. WEIGHTED GRAPH EXAMPLE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class WeightedGraph:                    |");
        System.out.println("|     def __init__(self):                 |");
        System.out.println("|         self.graph = {}                 |");
        System.out.println("|                                         |");
        System.out.println("|     def add_edge(self, vertex1, vertex2, weight): |");
        System.out.println("|         if vertex1 not in self.graph:   |");
        System.out.println("|             self.graph[vertex1] = []    |");
        System.out.println("|         if vertex2 not in self.graph:   |");
        System.out.println("|             self.graph[vertex2] = []    |");
        System.out.println("|         self.graph[vertex1].append((vertex2, weight)) |");
        System.out.println("|         self.graph[vertex2].append((vertex1, weight)) |");
        System.out.println("|                                         |");
        System.out.println("| # Usage example                         |");
        System.out.println("| g = Graph()                             |");
        System.out.println("| g.add_edge('A', 'B')                    |");
        System.out.println("| g.add_edge('B', 'C')                    |");
        System.out.println("| g.add_edge('C', 'D')                    |");
        System.out.println("| g.add_edge('D', 'A')                    |");
        System.out.println("| print(g.bfs('A'))  # ['A', 'B', 'D', 'C'] |");
        System.out.println("+-------------------------------------------+");
    }

    /**
     * Shows Python Algorithm implementations including sorting, searching, and dynamic programming
     */
    public void showPythonAlgorithms() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON ALGORITHMS");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Algorithms are step-by-step procedures for solving problems.");
        System.out.println();
        System.out.println("1. SORTING ALGORITHMS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Bubble Sort - O(n²)                   |");
        System.out.println("| def bubble_sort(arr):                   |");
        System.out.println("|     n = len(arr)                        |");
        System.out.println("|     for i in range(n):                  |");
        System.out.println("|         for j in range(0, n - i - 1):   |");
        System.out.println("|             if arr[j] > arr[j + 1]:     |");
        System.out.println("|                 arr[j], arr[j + 1] = arr[j + 1], arr[j] |");
        System.out.println("|     return arr                          |");
        System.out.println("|                                         |");
        System.out.println("| # Quick Sort - O(n log n) average       |");
        System.out.println("| def quick_sort(arr):                    |");
        System.out.println("|     if len(arr) <= 1:                  |");
        System.out.println("|         return arr                      |");
        System.out.println("|     pivot = arr[len(arr) // 2]          |");
        System.out.println("|     left = [x for x in arr if x < pivot] |");
        System.out.println("|     middle = [x for x in arr if x == pivot] |");
        System.out.println("|     right = [x for x in arr if x > pivot] |");
        System.out.println("|     return quick_sort(left) + middle + quick_sort(right) |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. SEARCH ALGORITHMS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Linear Search - O(n)                  |");
        System.out.println("| def linear_search(arr, target):         |");
        System.out.println("|     for i, value in enumerate(arr):     |");
        System.out.println("|         if value == target:             |");
        System.out.println("|             return i                    |");
        System.out.println("|     return -1  # Not found              |");
        System.out.println("|                                         |");
        System.out.println("| # Binary Search - O(log n)              |");
        System.out.println("| def binary_search(arr, target):         |");
        System.out.println("|     left, right = 0, len(arr) - 1       |");
        System.out.println("|     while left <= right:                |");
        System.out.println("|         mid = (left + right) // 2        |");
        System.out.println("|         if arr[mid] == target:           |");
        System.out.println("|             return mid                   |");
        System.out.println("|         elif arr[mid] < target:          |");
        System.out.println("|             left = mid + 1               |");
        System.out.println("|         else:                           |");
        System.out.println("|             right = mid - 1              |");
        System.out.println("|     return -1  # Not found              |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. DYNAMIC PROGRAMMING:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Fibonacci with Memoization            |");
        System.out.println("| def fibonacci_memo(n, memo={}):         |");
        System.out.println("|     if n in memo:                       |");
        System.out.println("|         return memo[n]                  |");
        System.out.println("|     if n <= 2:                         |");
        System.out.println("|         return 1                        |");
        System.out.println("|     memo[n] = fibonacci_memo(n-1, memo) + fibonacci_memo(n-2, memo) |");
        System.out.println("|     return memo[n]                      |");
        System.out.println("|                                         |");
        System.out.println("| # Longest Common Subsequence            |");
        System.out.println("| def lcs(str1, str2):                    |");
        System.out.println("|     m, n = len(str1), len(str2)         |");
        System.out.println("|     dp = [[0] * (n + 1) for _ in range(m + 1)] |");
        System.out.println("|     for i in range(1, m + 1):           |");
        System.out.println("|         for j in range(1, n + 1):       |");
        System.out.println("|             if str1[i-1] == str2[j-1]:  |");
        System.out.println("|                 dp[i][j] = dp[i-1][j-1] + 1 |");
        System.out.println("|             else:                       |");
        System.out.println("|                 dp[i][j] = max(dp[i-1][j], dp[i][j-1]) |");
        System.out.println("|     return dp[m][n]                     |");
        System.out.println("|                                         |");
        System.out.println("| # Example usage                         |");
        System.out.println("| print(fibonacci_memo(10))  # 55         |");
        System.out.println("| print(lcs('ABCDGH', 'AEDFHR'))  # 3     |");
        System.out.println("+-------------------------------------------+");
    }
}