"""
Java Control Structures - Control flow and decision-making constructs
"""


class JavaControlStructures:
    def __init__(self):
        pass

    def show_java_strings(self):
        """Displays Java string manipulation"""
        print("\n" + "=" * 70)
        print(">> JAVA STRING MANIPULATION")
        print("=" * 70)
        print()
        print("Strings in Java are objects that represent sequences of characters:")
        print()
        print("String Creation:")
        print('  String name = "John";           // String literal')
        print('  String city = new String("NYC"); // String object')
        print()
        print("String Methods:")
        print('  length()        "Hello".length()           // 5')
        print('  charAt(i)       "Hello".charAt(1)          // "e"')
        print('  substring(i,j)  "Hello".substring(1,4)     // "ell"')
        print('  indexOf(s)      "Hello".indexOf("l")       // 2')
        print('  toLowerCase()   "Hello".toLowerCase()       // "hello"')
        print('  toUpperCase()   "Hello".toUpperCase()       // "HELLO"')
        print()
        print("String Concatenation:")
        print('  String full = "Hello" + " " + "World";')
        print('  String full = name.concat(" Doe");')
        print()
        print("String Comparison:")
        print('  str1.equals(str2)        // Content comparison')
        print('  str1.equalsIgnoreCase(str2)  // Case-insensitive')

    def show_java_math(self):
        """Displays Java math operations"""
        print("\n" + "=" * 70)
        print(">> JAVA MATH OPERATIONS")
        print("=" * 70)
        print()
        print("Java Math class provides mathematical functions:")
        print()
        print("Common Math Methods:")
        print("  Math.max(a,b)     Math.max(5, 10)      // 10")
        print("  Math.min(a,b)     Math.min(5, 10)      // 5")
        print("  Math.abs(a)       Math.abs(-4.7)       // 4.7")
        print("  Math.sqrt(a)      Math.sqrt(64)        // 8.0")
        print("  Math.pow(a,b)     Math.pow(2, 3)       // 8.0")
        print("  Math.round(a)     Math.round(4.6)      // 5")
        print("  Math.ceil(a)      Math.ceil(4.3)       // 5.0")
        print("  Math.floor(a)     Math.floor(4.7)      // 4.0")
        print()
        print("Mathematical Constants:")
        print("  Math.PI           // 3.14159...")
        print("  Math.E            // 2.71828...")
        print()
        print("Random Numbers:")
        print("  Math.random()               // 0.0 to 1.0")
        print("  (int)(Math.random() * 100)  // 0 to 99")

    def show_java_booleans(self):
        """Displays Java boolean logic"""
        print("\n" + "=" * 70)
        print(">> JAVA BOOLEAN LOGIC")
        print("=" * 70)
        print()
        print("Boolean variables can hold true or false values:")
        print()
        print("Boolean Declaration:")
        print("  boolean isActive = true;")
        print("  boolean isComplete = false;")
        print("  boolean result = (10 > 5);    // true")
        print()
        print("Boolean Operations:")
        print("  &&  AND operator    true && false   // false")
        print("  ||  OR operator     true || false   // true")
        print("  !   NOT operator    !true           // false")
        print()
        print("Comparison Results:")
        print("  int x = 10;")
        print("  boolean a = (x > 5);     // true")
        print("  boolean b = (x == 10);   // true")
        print("  boolean c = (x < 5);     // false")
        print()
        print("Boolean in Conditions:")
        print("  if (isActive && !isComplete) {")
        print("      System.out.println(\"Processing...\");")
        print("  }")

    def show_java_if_else(self):
        """Displays Java if-else conditional statements"""
        print("\n" + "=" * 70)
        print(">> JAVA IF-ELSE CONDITIONAL STATEMENTS")
        print("=" * 70)
        print()
        print("Conditional statements execute code based on conditions:")
        print()
        print("1. Simple if statement:")
        print("   if (condition) {")
        print("       // code to execute if true")
        print("   }")
        print()
        print("2. if-else statement:")
        print("   if (condition) {")
        print("       // code if true")
        print("   } else {")
        print("       // code if false")
        print("   }")
        print()
        print("3. if-else if-else statement:")
        print("   if (condition1) {")
        print("       // code for condition1")
        print("   } else if (condition2) {")
        print("       // code for condition2")
        print("   } else {")
        print("       // code if all conditions false")
        print("   }")
        print()
        print("Example:")
        print("   int age = 18;")
        print("   if (age >= 18) {")
        print('       System.out.println("Adult");')
        print("   } else {")
        print('       System.out.println("Minor");')
        print("   }")

    def show_java_switch(self):
        """Displays Java switch statements"""
        print("\n" + "=" * 70)
        print(">> JAVA SWITCH STATEMENTS")
        print("=" * 70)
        print()
        print("Switch statements test a variable against many values:")
        print()
        print("Basic Switch Syntax:")
        print("   switch (variable) {")
        print("       case value1:")
        print("           // code for value1")
        print("           break;")
        print("       case value2:")
        print("           // code for value2")
        print("           break;")
        print("       default:")
        print("           // default code")
        print("   }")
        print()
        print("Example:")
        print("   int day = 3;")
        print("   switch (day) {")
        print("       case 1:")
        print('           System.out.println("Monday");')
        print("           break;")
        print("       case 2:")
        print('           System.out.println("Tuesday");')
        print("           break;")
        print("       default:")
        print('           System.out.println("Other day");')
        print("   }")
        print()
        print("Remember: break; prevents fall-through to next case")

    def show_java_while_loop(self):
        """Displays Java while loops"""
        print("\n" + "=" * 70)
        print(">> JAVA WHILE LOOPS")
        print("=" * 70)
        print()
        print("While loops repeat code as long as a condition is true:")
        print()
        print("1. While Loop:")
        print("   int i = 0;")
        print("   while (i < 5) {")
        print("       System.out.println(i);")
        print("       i++;")
        print("   }")
        print("   // Prints: 0, 1, 2, 3, 4")
        print()
        print("2. Do-While Loop:")
        print("   int j = 0;")
        print("   do {")
        print("       System.out.println(j);")
        print("       j++;")
        print("   } while (j < 5);")
        print()
        print("Key Differences:")
        print("* while: Tests condition before executing")
        print("* do-while: Executes at least once, then tests condition")
        print()
        print("Important: Always ensure the condition can become false")
        print("to avoid infinite loops!")

    def show_java_for_loop(self):
        """Displays Java for loops"""
        print("\n" + "=" * 70)
        print(">> JAVA FOR LOOPS")
        print("=" * 70)
        print()
        print("For loops are ideal when you know the number of iterations:")
        print()
        print("1. Traditional For Loop:")
        print("   for (initialization; condition; increment) {")
        print("       // code to repeat")
        print("   }")
        print()
        print("   for (int i = 0; i < 5; i++) {")
        print("       System.out.println(i);")
        print("   }")
        print("   // Prints: 0, 1, 2, 3, 4")
        print()
        print("2. Enhanced For Loop (for-each):")
        print("   int[] numbers = {1, 2, 3, 4, 5};")
        print("   for (int num : numbers) {")
        print("       System.out.println(num);")
        print("   }")
        print()
        print("3. Nested For Loops:")
        print("   for (int i = 1; i <= 3; i++) {")
        print("       for (int j = 1; j <= 3; j++) {")
        print("           System.out.print(i + \",\" + j + \" \");")
        print("       }")
        print("   }")

    def show_java_break_continue(self):
        """Displays Java break and continue statements"""
        print("\n" + "=" * 70)
        print(">> JAVA BREAK & CONTINUE")
        print("=" * 70)
        print()
        print("Break and continue control loop execution:")
        print()
        print("1. break - Exits the loop completely:")
        print("   for (int i = 0; i < 10; i++) {")
        print("       if (i == 5) {")
        print("           break;  // Exits loop when i is 5")
        print("       }")
        print("       System.out.println(i);")
        print("   }")
        print("   // Prints: 0, 1, 2, 3, 4")
        print()
        print("2. continue - Skips current iteration:")
        print("   for (int i = 0; i < 5; i++) {")
        print("       if (i == 2) {")
        print("           continue;  // Skips when i is 2")
        print("       }")
        print("       System.out.println(i);")
        print("   }")
        print("   // Prints: 0, 1, 3, 4")
        print()
        print("3. Labeled breaks (for nested loops):")
        print("   outer: for (int i = 0; i < 3; i++) {")
        print("       for (int j = 0; j < 3; j++) {")
        print("           if (i == 1 && j == 1) {")
        print("               break outer;  // Exits outer loop")
        print("           }")
        print("       }")
        print("   }")