package com.prolanlab.tutorials.python.classesandoop;

import com.prolanlab.Main;

/**
 * Python Classes and Object-Oriented Programming (OOP) Tutorial
 * Contains methods covering Python OOP concepts, classes, objects, and related topics
 */
public class PythonClassesAndOOP {
    
    /**
     * Displays an overview of Python Object-Oriented Programming concepts
     */
    public void showPythonOOP() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON OBJECT-ORIENTED PROGRAMMING");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("OOP is a programming paradigm based on objects and classes.");
        System.out.println();
        System.out.println("1. OOP PRINCIPLES:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| 1. Encapsulation - Data hiding          |");
        System.out.println("| 2. Inheritance - Code reusability       |");
        System.out.println("| 3. Polymorphism - Multiple forms        |");
        System.out.println("| 4. Abstraction - Simplified interface   |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. CLASSES AND OBJECTS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Class definition                      |");
        System.out.println("| class Car:                              |");
        System.out.println("|     def __init__(self, brand, model):   |");
        System.out.println("|         self.brand = brand              |");
        System.out.println("|         self.model = model              |");
        System.out.println("|                                         |");
        System.out.println("| # Object creation                       |");
        System.out.println("| my_car = Car('Toyota', 'Camry')         |");
        System.out.println("| print(my_car.brand)  # 'Toyota'        |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. METHODS AND ATTRIBUTES:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Person:                           |");
        System.out.println("|     species = 'Homo sapiens'  # Class attribute |");
        System.out.println("|                                         |");
        System.out.println("|     def __init__(self, name, age):      |");
        System.out.println("|         self.name = name  # Instance attribute |");
        System.out.println("|         self.age = age                  |");
        System.out.println("|                                         |");
        System.out.println("|     def greet(self):  # Instance method |");
        System.out.println("|         return f'Hi, I am {self.name}'  |");
        System.out.println("|                                         |");
        System.out.println("| person = Person('Alice', 30)            |");
        System.out.println("| print(person.greet())  # 'Hi, I am Alice' |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Explains Python classes and objects with creation and usage examples
     */
    public void showPythonClassesObjects() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> CLASSES AND OBJECTS");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Classes are blueprints for creating objects.");
        System.out.println();
        System.out.println("1. DEFINING A CLASS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Student:                          |");
        System.out.println("|     # Class variable (shared by all)    |");
        System.out.println("|     school_name = 'Python High School'  |");
        System.out.println("|                                         |");
        System.out.println("|     # Constructor method                |");
        System.out.println("|     def __init__(self, name, grade):    |");
        System.out.println("|         # Instance variables (unique)    |");
        System.out.println("|         self.name = name                |");
        System.out.println("|         self.grade = grade              |");
        System.out.println("|         self.courses = []               |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. CREATING AND USING OBJECTS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Creating objects (instances)          |");
        System.out.println("| student1 = Student('Alice', 'A')        |");
        System.out.println("| student2 = Student('Bob', 'B')          |");
        System.out.println("|                                         |");
        System.out.println("| # Accessing attributes                  |");
        System.out.println("| print(student1.name)        # 'Alice'  |");
        System.out.println("| print(student1.school_name) # 'Python High School' |");
        System.out.println("|                                         |");
        System.out.println("| # Modifying attributes                  |");
        System.out.println("| student1.grade = 'A+'                  |");
        System.out.println("| student1.courses.append('Math')        |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. INSTANCE vs CLASS ATTRIBUTES:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Each object has its own instance attributes |");
        System.out.println("| print(student1.name)  # 'Alice'        |");
        System.out.println("| print(student2.name)  # 'Bob'          |");
        System.out.println("|                                         |");
        System.out.println("| # All objects share class attributes    |");
        System.out.println("| Student.school_name = 'New School'     |");
        System.out.println("| print(student1.school_name) # 'New School' |");
        System.out.println("| print(student2.school_name) # 'New School' |");
        System.out.println("|                                         |");
        System.out.println("| # Check object type                     |");
        System.out.println("| print(type(student1))  # <class '__main__.Student'> |");
        System.out.println("| print(isinstance(student1, Student)) # True |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Explains the self parameter and its role in Python classes
     */
    public void showPythonSelfParameter() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> SELF PARAMETER");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Self parameter refers to the instance of the class.");
        System.out.println();
        System.out.println("1. UNDERSTANDING SELF:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Circle:                           |");
        System.out.println("|     def __init__(self, radius):         |");
        System.out.println("|         # self refers to the specific   |");
        System.out.println("|         # instance being created        |");
        System.out.println("|         self.radius = radius           |");
        System.out.println("|                                         |");
        System.out.println("|     def get_area(self):                 |");
        System.out.println("|         # self accesses instance data   |");
        System.out.println("|         return 3.14159 * self.radius ** 2 |");
        System.out.println("|                                         |");
        System.out.println("| # When calling methods, Python          |");
        System.out.println("| # automatically passes self            |");
        System.out.println("| circle = Circle(5)                      |");
        System.out.println("| area = circle.get_area()  # area = 78.54 |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. SELF IN DIFFERENT METHODS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class BankAccount:                      |");
        System.out.println("|     def __init__(self, owner, balance=0): |");
        System.out.println("|         self.owner = owner              |");
        System.out.println("|         self.balance = balance          |");
        System.out.println("|                                         |");
        System.out.println("|     def deposit(self, amount):          |");
        System.out.println("|         self.balance += amount          |");
        System.out.println("|         return self.balance             |");
        System.out.println("|                                         |");
        System.out.println("|     def withdraw(self, amount):         |");
        System.out.println("|         if amount <= self.balance:      |");
        System.out.println("|             self.balance -= amount      |");
        System.out.println("|         return self.balance             |");
        System.out.println("|                                         |");
        System.out.println("|     def get_info(self):                 |");
        System.out.println("|         return f'{self.owner}: ${self.balance}' |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. SELF vs OTHER NAMES:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # 'self' is just a convention          |");
        System.out.println("| # You could use any name, but don't!    |");
        System.out.println("| class Example:                          |");
        System.out.println("|     def __init__(this, value):  # Works but bad |");
        System.out.println("|         this.value = value              |");
        System.out.println("|                                         |");
        System.out.println("| # Always use 'self' - it's the standard |");
        System.out.println("| # and expected by other Python developers |");
        System.out.println("|                                         |");
        System.out.println("| # Multiple instances have different self |");
        System.out.println("| account1 = BankAccount('Alice', 100)    |");
        System.out.println("| account2 = BankAccount('Bob', 200)      |");
        System.out.println("| # Each method call uses their own 'self' |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Demonstrates different types of methods in Python classes
     */
    public void showPythonMethods() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON METHODS");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Methods are functions defined inside a class.");
        System.out.println();
        System.out.println("1. INSTANCE METHODS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Calculator:                       |");
        System.out.println("|     def __init__(self, name):           |");
        System.out.println("|         self.name = name                |");
        System.out.println("|         self.result = 0                 |");
        System.out.println("|                                         |");
        System.out.println("|     # Instance methods work with 'self' |");
        System.out.println("|     def add(self, x, y):                |");
        System.out.println("|         self.result = x + y             |");
        System.out.println("|         return self.result              |");
        System.out.println("|                                         |");
        System.out.println("|     def multiply(self, x, y):           |");
        System.out.println("|         self.result = x * y             |");
        System.out.println("|         return self.result              |");
        System.out.println("|                                         |");
        System.out.println("| calc = Calculator('MyCalc')             |");
        System.out.println("| print(calc.add(5, 3))      # 8         |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. CLASS METHODS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Person:                           |");
        System.out.println("|     population = 0                      |");
        System.out.println("|                                         |");
        System.out.println("|     def __init__(self, name):           |");
        System.out.println("|         self.name = name                |");
        System.out.println("|         Person.population += 1          |");
        System.out.println("|                                         |");
        System.out.println("|     @classmethod                        |");
        System.out.println("|     def get_population(cls):            |");
        System.out.println("|         return cls.population           |");
        System.out.println("|                                         |");
        System.out.println("|     @classmethod                        |");
        System.out.println("|     def create_anonymous(cls):          |");
        System.out.println("|         return cls('Anonymous')         |");
        System.out.println("|                                         |");
        System.out.println("| # Call class methods on class or instance |");
        System.out.println("| print(Person.get_population())  # 0    |");
        System.out.println("| person1 = Person('Alice')               |");
        System.out.println("| print(Person.get_population())  # 1    |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. STATIC METHODS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class MathUtils:                        |");
        System.out.println("|     # Static methods don't need self or cls |");
        System.out.println("|     @staticmethod                       |");
        System.out.println("|     def add_numbers(x, y):              |");
        System.out.println("|         return x + y                    |");
        System.out.println("|                                         |");
        System.out.println("|     @staticmethod                       |");
        System.out.println("|     def is_even(number):                |");
        System.out.println("|         return number % 2 == 0          |");
        System.out.println("|                                         |");
        System.out.println("| # Call static methods without creating instance |");
        System.out.println("| print(MathUtils.add_numbers(5, 3))  # 8 |");
        System.out.println("| print(MathUtils.is_even(4))         # True |");
        System.out.println("|                                         |");
        System.out.println("| # Can also call on instances            |");
        System.out.println("| utils = MathUtils()                     |");
        System.out.println("| print(utils.add_numbers(2, 3))     # 5 |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Explains Python properties for getter/setter access control
     */
    public void showPythonProperties() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON PROPERTIES");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Properties provide getter/setter access control.");
        System.out.println();
        System.out.println("1. USING @property DECORATOR:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Temperature:                      |");
        System.out.println("|     def __init__(self, celsius=0):      |");
        System.out.println("|         self._celsius = celsius         |");
        System.out.println("|                                         |");
        System.out.println("|     @property                           |");
        System.out.println("|     def celsius(self):                  |");
        System.out.println("|         return self._celsius            |");
        System.out.println("|                                         |");
        System.out.println("|     @celsius.setter                     |");
        System.out.println("|     def celsius(self, value):           |");
        System.out.println("|         if value < -273.15:             |");
        System.out.println("|             raise ValueError('Below absolute zero') |");
        System.out.println("|         self._celsius = value           |");
        System.out.println("|                                         |");
        System.out.println("|     @property                           |");
        System.out.println("|     def fahrenheit(self):               |");
        System.out.println("|         return (self._celsius * 9/5) + 32 |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. READ-ONLY PROPERTIES:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Circle:                           |");
        System.out.println("|     def __init__(self, radius):         |");
        System.out.println("|         self._radius = radius           |");
        System.out.println("|                                         |");
        System.out.println("|     @property                           |");
        System.out.println("|     def radius(self):                   |");
        System.out.println("|         return self._radius             |");
        System.out.println("|                                         |");
        System.out.println("|     @property                           |");
        System.out.println("|     def area(self):  # Read-only        |");
        System.out.println("|         return 3.14159 * self._radius ** 2 |");
        System.out.println("|                                         |");
        System.out.println("|     @property                           |");
        System.out.println("|     def diameter(self):  # Read-only    |");
        System.out.println("|         return 2 * self._radius         |");
        System.out.println("|                                         |");
        System.out.println("| circle = Circle(5)                      |");
        System.out.println("| print(circle.area)      # 78.54        |");
        System.out.println("| # circle.area = 100  # Error! Read-only |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. PROPERTY WITH VALIDATION:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Person:                           |");
        System.out.println("|     def __init__(self, name, age):      |");
        System.out.println("|         self._name = name               |");
        System.out.println("|         self._age = age                 |");
        System.out.println("|                                         |");
        System.out.println("|     @property                           |");
        System.out.println("|     def age(self):                      |");
        System.out.println("|         return self._age                |");
        System.out.println("|                                         |");
        System.out.println("|     @age.setter                         |");
        System.out.println("|     def age(self, value):               |");
        System.out.println("|         if not isinstance(value, int):   |");
        System.out.println("|             raise TypeError('Age must be integer') |");
        System.out.println("|         if value < 0 or value > 150:    |");
        System.out.println("|             raise ValueError('Invalid age') |");
        System.out.println("|         self._age = value               |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Demonstrates Python inheritance and method overriding
     */
    public void showPythonInheritance() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON INHERITANCE");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Inheritance allows classes to inherit from other classes.");
        System.out.println();
        System.out.println("1. BASIC INHERITANCE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Parent class (Base class)             |");
        System.out.println("| class Animal:                           |");
        System.out.println("|     def __init__(self, name, species):  |");
        System.out.println("|         self.name = name                |");
        System.out.println("|         self.species = species          |");
        System.out.println("|                                         |");
        System.out.println("|     def make_sound(self):               |");
        System.out.println("|         return 'Some generic sound'     |");
        System.out.println("|                                         |");
        System.out.println("|     def info(self):                     |");
        System.out.println("|         return f'{self.name} is a {self.species}' |");
        System.out.println("|                                         |");
        System.out.println("| # Child class (Derived class)           |");
        System.out.println("| class Dog(Animal):                      |");
        System.out.println("|     def __init__(self, name, breed):    |");
        System.out.println("|         super().__init__(name, 'Dog')   |");
        System.out.println("|         self.breed = breed              |");
        System.out.println("|                                         |");
        System.out.println("|     def make_sound(self):  # Override   |");
        System.out.println("|         return 'Woof!'                  |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. METHOD OVERRIDING:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Cat(Animal):                      |");
        System.out.println("|     def __init__(self, name, indoor=True): |");
        System.out.println("|         super().__init__(name, 'Cat')   |");
        System.out.println("|         self.indoor = indoor            |");
        System.out.println("|                                         |");
        System.out.println("|     def make_sound(self):               |");
        System.out.println("|         return 'Meow!'                  |");
        System.out.println("|                                         |");
        System.out.println("|     def info(self):  # Override and extend |");
        System.out.println("|         base_info = super().info()      |");
        System.out.println("|         location = 'indoor' if self.indoor else 'outdoor' |");
        System.out.println("|         return f'{base_info} ({location})' |");
        System.out.println("|                                         |");
        System.out.println("| # Using inherited classes               |");
        System.out.println("| dog = Dog('Buddy', 'Golden Retriever')  |");
        System.out.println("| cat = Cat('Whiskers', True)             |");
        System.out.println("| print(dog.make_sound())  # 'Woof!'     |");
        System.out.println("| print(cat.info())  # 'Whiskers is a Cat (indoor)' |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. MULTIPLE INHERITANCE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Flyable:                          |");
        System.out.println("|     def fly(self):                      |");
        System.out.println("|         return 'Flying through the air' |");
        System.out.println("|                                         |");
        System.out.println("| class Swimmable:                        |");
        System.out.println("|     def swim(self):                     |");
        System.out.println("|         return 'Swimming in water'      |");
        System.out.println("|                                         |");
        System.out.println("| # Multiple inheritance                  |");
        System.out.println("| class Duck(Animal, Flyable, Swimmable): |");
        System.out.println("|     def __init__(self, name):           |");
        System.out.println("|         Animal.__init__(self, name, 'Duck') |");
        System.out.println("|                                         |");
        System.out.println("|     def make_sound(self):               |");
        System.out.println("|         return 'Quack!'                 |");
        System.out.println("|                                         |");
        System.out.println("| duck = Duck('Donald')                   |");
        System.out.println("| print(duck.fly())    # 'Flying through the air' |");
        System.out.println("| print(duck.swim())   # 'Swimming in water' |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Explains Python polymorphism and duck typing
     */
    public void showPythonPolymorphism() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON POLYMORPHISM");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Polymorphism allows objects of different types to be treated uniformly.");
        System.out.println();
        System.out.println("1. METHOD OVERRIDING POLYMORPHISM:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Shape:                            |");
        System.out.println("|     def area(self):                     |");
        System.out.println("|         raise NotImplementedError('Subclass must implement') |");
        System.out.println("|                                         |");
        System.out.println("|     def perimeter(self):                |");
        System.out.println("|         raise NotImplementedError('Subclass must implement') |");
        System.out.println("|                                         |");
        System.out.println("| class Rectangle(Shape):                 |");
        System.out.println("|     def __init__(self, width, height):  |");
        System.out.println("|         self.width = width              |");
        System.out.println("|         self.height = height            |");
        System.out.println("|                                         |");
        System.out.println("|     def area(self):                     |");
        System.out.println("|         return self.width * self.height |");
        System.out.println("|                                         |");
        System.out.println("|     def perimeter(self):                |");
        System.out.println("|         return 2 * (self.width + self.height) |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. POLYMORPHIC BEHAVIOR:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Circle(Shape):                    |");
        System.out.println("|     def __init__(self, radius):         |");
        System.out.println("|         self.radius = radius            |");
        System.out.println("|                                         |");
        System.out.println("|     def area(self):                     |");
        System.out.println("|         return 3.14159 * self.radius ** 2 |");
        System.out.println("|                                         |");
        System.out.println("|     def perimeter(self):                |");
        System.out.println("|         return 2 * 3.14159 * self.radius |");
        System.out.println("|                                         |");
        System.out.println("| # Polymorphic function                  |");
        System.out.println("| def describe_shape(shape):              |");
        System.out.println("|     print(f'Area: {shape.area():.2f}')  |");
        System.out.println("|     print(f'Perimeter: {shape.perimeter():.2f}') |");
        System.out.println("|                                         |");
        System.out.println("| # Same function works with different shapes |");
        System.out.println("| rectangle = Rectangle(5, 3)             |");
        System.out.println("| circle = Circle(4)                      |");
        System.out.println("| describe_shape(rectangle)  # Uses Rectangle methods |");
        System.out.println("| describe_shape(circle)     # Uses Circle methods |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. DUCK TYPING:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # If it walks like a duck and quacks    |");
        System.out.println("| # like a duck, then it is a duck        |");
        System.out.println("|                                         |");
        System.out.println("| class FileWriter:                       |");
        System.out.println("|     def write(self, text):              |");
        System.out.println("|         with open('file.txt', 'w') as f: |");
        System.out.println("|             f.write(text)               |");
        System.out.println("|                                         |");
        System.out.println("| class ConsoleWriter:                    |");
        System.out.println("|     def write(self, text):              |");
        System.out.println("|         print(text)                     |");
        System.out.println("|                                         |");
        System.out.println("| # Function works with any object that   |");
        System.out.println("| # has a 'write' method                  |");
        System.out.println("| def save_data(writer, data):            |");
        System.out.println("|     writer.write(data)                  |");
        System.out.println("|                                         |");
        System.out.println("| save_data(FileWriter(), 'Hello File')   |");
        System.out.println("| save_data(ConsoleWriter(), 'Hello Console') |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Demonstrates Python encapsulation and access control
     */
    public void showPythonEncapsulation() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> PYTHON ENCAPSULATION");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Encapsulation hides internal implementation details.");
        System.out.println();
        System.out.println("1. PRIVATE ATTRIBUTES:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class BankAccount:                      |");
        System.out.println("|     def __init__(self, initial_balance): |");
        System.out.println("|         # Public attribute              |");
        System.out.println("|         self.account_holder = 'User'    |");
        System.out.println("| \t\t\t                                         |");
        System.out.println("|         # Protected attribute (convention) |");
        System.out.println("|         self._account_number = 'ACC123'  |");
        System.out.println("|                                         |");
        System.out.println("|         # Private attribute (name mangling) |");
        System.out.println("|         self.__balance = initial_balance |");
        System.out.println("|                                         |");
        System.out.println("|     def get_balance(self):  # Public method |");
        System.out.println("|         return self.__balance           |");
        System.out.println("|                                         |");
        System.out.println("|     def deposit(self, amount):          |");
        System.out.println("|         if self.__validate_amount(amount): |");
        System.out.println("|             self.__balance += amount    |");
        System.out.println("|                                         |");
        System.out.println("|     def __validate_amount(self, amount): # Private method |");
        System.out.println("|         return amount > 0               |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. ACCESS CONTROL:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| account = BankAccount(1000)             |");
        System.out.println("|                                         |");
        System.out.println("| # Public access - works                 |");
        System.out.println("| print(account.account_holder)  # 'User' |");
        System.out.println("|                                         |");
        System.out.println("| # Protected access - works but discouraged |");
        System.out.println("| print(account._account_number)  # 'ACC123' |");
        System.out.println("|                                         |");
        System.out.println("| # Private access - AttributeError       |");
        System.out.println("| # print(account.__balance)  # Error!    |");
        System.out.println("|                                         |");
        System.out.println("| # Access through name mangling (not recommended) |");
        System.out.println("| print(account._BankAccount__balance)  # 1000 |");
        System.out.println("|                                         |");
        System.out.println("| # Proper access through public methods  |");
        System.out.println("| print(account.get_balance())  # 1000    |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. GETTERS AND SETTERS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Student:                          |");
        System.out.println("|     def __init__(self, name):           |");
        System.out.println("|         self.__name = name              |");
        System.out.println("|         self.__grades = []              |");
        System.out.println("|                                         |");
        System.out.println("|     # Getter methods                    |");
        System.out.println("|     def get_name(self):                 |");
        System.out.println("|         return self.__name              |");
        System.out.println("|                                         |");
        System.out.println("|     def get_grades(self):               |");
        System.out.println("|         return self.__grades.copy()  # Return copy |");
        System.out.println("|                                         |");
        System.out.println("|     # Setter methods with validation    |");
        System.out.println("|     def add_grade(self, grade):         |");
        System.out.println("|         if 0 <= grade <= 100:           |");
        System.out.println("|             self.__grades.append(grade) |");
        System.out.println("|         else:                           |");
        System.out.println("|             raise ValueError('Invalid grade') |");
        System.out.println("|                                         |");
        System.out.println("|     def get_average(self):              |");
        System.out.println("|         if self.__grades:               |");
        System.out.println("|             return sum(self.__grades) / len(self.__grades) |");
        System.out.println("|         return 0                        |");
        System.out.println("+-------------------------------------------+");
    }
    
    /**
     * Explains Python inner classes and their usage
     */
    public void showPythonInnerClasses() {
        System.out.println("\n" + "=".repeat(75));
        System.out.println(">> INNER CLASSES");
        System.out.println("=".repeat(75));
        System.out.println();
        System.out.println("Inner classes are classes defined inside other classes.");
        System.out.println();
        System.out.println("1. BASIC INNER CLASS:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class Computer:                         |");
        System.out.println("|     def __init__(self, brand):          |");
        System.out.println("|         self.brand = brand              |");
        System.out.println("|         self.cpu = self.CPU()           |");
        System.out.println("|         self.gpu = self.GPU()           |");
        System.out.println("|                                         |");
        System.out.println("|     class CPU:  # Inner class           |");
        System.out.println("|         def __init__(self):             |");
        System.out.println("|             self.cores = 4              |");
        System.out.println("|             self.speed = '3.2 GHz'      |");
        System.out.println("|                                         |");
        System.out.println("|         def process(self):              |");
        System.out.println("|             return 'Processing data...' |");
        System.out.println("|                                         |");
        System.out.println("|     class GPU:  # Another inner class   |");
        System.out.println("|         def __init__(self):             |");
        System.out.println("|             self.memory = '8GB'         |");
        System.out.println("|                                         |");
        System.out.println("|         def render(self):               |");
        System.out.println("|             return 'Rendering graphics...' |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("2. ACCESSING INNER CLASSES:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| # Create outer class instance           |");
        System.out.println("| my_computer = Computer('Dell')          |");
        System.out.println("|                                         |");
        System.out.println("| # Access inner class through outer instance |");
        System.out.println("| print(my_computer.cpu.cores)    # 4    |");
        System.out.println("| print(my_computer.cpu.process()) # 'Processing data...' |");
        System.out.println("| print(my_computer.gpu.render())  # 'Rendering graphics...' |");
        System.out.println("|                                         |");
        System.out.println("| # Create inner class directly           |");
        System.out.println("| standalone_cpu = Computer.CPU()         |");
        System.out.println("| print(standalone_cpu.process())         |");
        System.out.println("+-------------------------------------------+");
        System.out.println();
        System.out.println("3. INNER CLASS WITH OUTER REFERENCE:");
        System.out.println("+-------------------------------------------+");
        System.out.println("| class University:                       |");
        System.out.println("|     def __init__(self, name):           |");
        System.out.println("|         self.name = name                |");
        System.out.println("|         self.students = []              |");
        System.out.println("|                                         |");
        System.out.println("|     def enroll_student(self, student_name): |");
        System.out.println("|         student = self.Student(student_name, self) |");
        System.out.println("|         self.students.append(student)   |");
        System.out.println("|         return student                  |");
        System.out.println("|                                         |");
        System.out.println("|     class Student:                      |");
        System.out.println("|         def __init__(self, name, university): |");
        System.out.println("|             self.name = name            |");
        System.out.println("|             self.university = university # Reference to outer |");
        System.out.println("|             self.courses = []           |");
        System.out.println("|                                         |");
        System.out.println("|         def get_university_info(self):  |");
        System.out.println("|             return f'Student at {self.university.name}' |");
        System.out.println("|                                         |");
        System.out.println("| uni = University('MIT')                 |");
        System.out.println("| student = uni.enroll_student('Alice')   |");
        System.out.println("| print(student.get_university_info())  # 'Student at MIT' |");
        System.out.println("+-------------------------------------------+");
    }
}