class PythonFundamentals:
    def __init__(self):
        pass

    def show_python_intro(self):
        """Displays Python introduction and philosophy"""
        print("\n" + "=" * 70)
        print(">> PYTHON INTRODUCTION & PHILOSOPHY")
        print("=" * 70)
        print()
        print("Python is a high-level, interpreted programming language.")
        print()
        print("Python Philosophy (The Zen of Python):")
        print("* Beautiful is better than ugly")
        print("* Explicit is better than implicit")
        print("* Simple is better than complex")
        print("* Readability counts")
        print("* There should be one obvious way to do it")
        print()
        print("Key Features:")
        print("* Easy to learn and use")
        print("* Interpreted language")
        print("* Cross-platform")
        print("* Large standard library")
        print("* Dynamic typing")
        print("* Object-oriented and functional programming support")
        print()
        print("Basic Python Program:")
        print("+-------------------------------------------+")
        print("| # Hello World in Python                 |")
        print("| print('Hello, World!')                  |")
        print("+-------------------------------------------+")

    def show_python_syntax(self):
        """Displays Python syntax and indentation rules"""
        print("\n" + "=" * 70)
        print(">> PYTHON SYNTAX & INDENTATION RULES")
        print("=" * 70)
        print()
        print("Python syntax is designed for readability:")
        print()
        print("Key Syntax Rules:")
        print("* Indentation is significant (no curly braces)")
        print("* Use 4 spaces for indentation (recommended)")
        print("* Statements don't end with semicolons")
        print("* Case-sensitive language")
        print("* Comments start with # symbol")
        print()
        print("Indentation Example:")
        print("+-------------------------------------------+")
        print("| if 5 > 2:                               |")
        print("|     print('Five is greater than two!')  |")
        print("|     if True:                            |")
        print("|         print('Nested statement')       |")
        print("+-------------------------------------------+")
        print()
        print("Line Continuation:")
        print("  # Using backslash")
        print("  total = 1 + 2 + 3 + \\")
        print("          4 + 5 + 6")
        print()
        print("  # Using parentheses (preferred)")
        print("  total = (1 + 2 + 3 +")
        print("           4 + 5 + 6)")

    def show_python_statements(self):
        """Displays Python statements and execution"""
        print("\n" + "=" * 70)
        print(">> PYTHON STATEMENTS & EXECUTION")
        print("=" * 70)
        print()
        print("Python statements are instructions that Python can execute:")
        print()
        print("Types of Statements:")
        print("1. Expression statements:")
        print("   42")
        print("   3 + 4")
        print("   'Hello, World!'")
        print()
        print("2. Assignment statements:")
        print("   x = 5")
        print("   name = 'Alice'")
        print()
        print("3. Compound statements:")
        print("   if x > 0:")
        print("       print('Positive')")
        print()
        print("4. Import statements:")
        print("   import math")
        print("   from datetime import date")
        print()
        print("Interactive vs Script Mode:")
        print("* Interactive: Type commands one by one")
        print("* Script: Write code in .py files and run them")

    def show_python_print(self):
        """Displays Python print functions"""
        print("\n" + "=" * 70)
        print(">> PYTHON PRINT FUNCTIONS")
        print("=" * 70)
        print()
        print("The print() function displays output to the screen:")
        print()
        print("Basic Usage:")
        print("  print('Hello, World!')")
        print("  print(42)")
        print("  print(3.14159)")
        print()
        print("Print Multiple Values:")
        print("  print('Name:', 'Alice', 'Age:', 25)")
        print("  # Output: Name: Alice Age: 25")
        print()
        print("Print Parameters:")
        print("  print('A', 'B', 'C', sep='-')    # A-B-C")
        print("  print('Hello', end=' ')          # No newline")
        print("  print('World')                   # Hello World")
        print()
        print("Formatted Output:")
        print("  name = 'Bob'")
        print("  age = 30")
        print("  print(f'My name is {name} and I am {age} years old')")
        print("  print('My name is {} and I am {} years old'.format(name, age))")
        print("  print('My name is %s and I am %d years old' % (name, age))")

    def show_python_numbers(self):
        """Displays Python number output and formatting"""
        print("\n" + "=" * 70)
        print(">> PYTHON NUMBER OUTPUT & FORMATTING")
        print("=" * 70)
        print()
        print("Python handles different number types and formatting:")
        print()
        print("Number Types:")
        print("  integer = 42")
        print("  floating = 3.14159")
        print("  complex_num = 3 + 4j")
        print()
        print("Number Formatting:")
        print("  pi = 3.14159265")
        print("  print(f'{pi:.2f}')           # 3.14 (2 decimal places)")
        print("  print(f'{pi:.4f}')           # 3.1416 (4 decimal places)")
        print("  print(f'{1234:,}')           # 1,234 (thousands separator)")
        print("  print(f'{0.5:.2%}')          # 50.00% (percentage)")
        print()
        print("Scientific Notation:")
        print("  large = 1234567890")
        print("  print(f'{large:.2e}')        # 1.23e+09")
        print()
        print("Number Base Conversion:")
        print("  num = 255")
        print("  print(f'{num:b}')            # 11111111 (binary)")
        print("  print(f'{num:o}')            # 377 (octal)")
        print("  print(f'{num:x}')            # ff (hexadecimal)")

    def show_python_comments(self):
        """Displays Python comments and documentation"""
        print("\n" + "=" * 70)
        print(">> PYTHON COMMENTS & DOCUMENTATION")
        print("=" * 70)
        print()
        print("Comments help document your Python code:")
        print()
        print("1. Single-line comments:")
        print("   # This is a single-line comment")
        print("   x = 5  # This is an inline comment")
        print()
        print("2. Multi-line comments:")
        print("   '''")
        print("   This is a multi-line comment")
        print("   spanning several lines")
        print("   '''")
        print()
        print("3. Docstrings (for documentation):")
        print('   def greet(name):')
        print('       """')
        print('       Greet a person by name.')
        print('       ')
        print('       Args:')
        print('           name (str): The person\'s name')
        print('       ')
        print('       Returns:')
        print('           str: A greeting message')
        print('       """')
        print('       return f"Hello, {name}!"')
        print()
        print("Best Practices:")
        print("* Use # for short explanations")
        print("* Use docstrings for function/class documentation")
        print("* Keep comments updated with code changes")

    def show_python_variables(self):
        """Displays Python variables and assignment"""
        print("\n" + "=" * 70)
        print(">> PYTHON VARIABLES & ASSIGNMENT")
        print("=" * 70)
        print()
        print("Variables store data values in Python:")
        print()
        print("Variable Assignment:")
        print("  x = 5                    # Integer")
        print("  name = 'Alice'           # String")
        print("  price = 19.99            # Float")
        print("  is_active = True         # Boolean")
        print()
        print("Dynamic Typing:")
        print("  x = 5        # x is an integer")
        print("  x = 'Hello'  # Now x is a string")
        print("  x = [1,2,3]  # Now x is a list")
        print()
        print("Variable Naming Rules:")
        print("* Must start with letter or underscore")
        print("* Can contain letters, numbers, underscores")
        print("* Case-sensitive (age and Age are different)")
        print("* Cannot use Python keywords (if, for, class, etc.)")
        print()
        print("Naming Conventions:")
        print("* snake_case for variables and functions")
        print("* PascalCase for classes")
        print("* UPPER_CASE for constants")
        print("  first_name = 'John'")
        print("  MAX_SIZE = 100")

    def show_python_multiple_values(self):
        """Displays Python multiple value assignments"""
        print("\n" + "=" * 70)
        print(">> PYTHON MULTIPLE VALUE ASSIGNMENTS")
        print("=" * 70)
        print()
        print("Python allows assigning multiple values efficiently:")
        print()
        print("1. Multiple Assignment:")
        print("   x, y, z = 1, 2, 3")
        print("   print(x, y, z)  # Output: 1 2 3")
        print()
        print("2. Same Value to Multiple Variables:")
        print("   a = b = c = 0")
        print("   print(a, b, c)  # Output: 0 0 0")
        print()
        print("3. Unpacking Collections:")
        print("   fruits = ['apple', 'banana', 'cherry']")
        print("   x, y, z = fruits")
        print("   print(x)  # apple")
        print("   print(y)  # banana")
        print("   print(z)  # cherry")
        print()
        print("4. Swapping Variables:")
        print("   a = 5")
        print("   b = 10")
        print("   a, b = b, a  # Swap values")
        print("   print(a, b)  # Output: 10 5")
        print()
        print("5. Partial Unpacking:")
        print("   numbers = [1, 2, 3, 4, 5]")
        print("   first, *middle, last = numbers")
        print("   print(first)   # 1")
        print("   print(middle)  # [2, 3, 4]")
        print("   print(last)    # 5")

    def show_python_output_variables(self):
        """Displays Python variable output techniques"""
        print("\n" + "=" * 70)
        print(">> PYTHON VARIABLE OUTPUT TECHNIQUES")
        print("=" * 70)
        print()
        print("Python provides several ways to output variables:")
        print()
        print("1. Simple Variable Output:")
        print("  name = 'Alice'")
        print("  age = 25")
        print("  print(name)          # Alice")
        print("  print(age)           # 25")
        print()
        print("2. Multiple Variables:")
        print("  print(name, age)     # Alice 25")
        print("  print(name, age, sep='-')  # Alice-25")
        print()
        print("3. Formatted String Literals (f-strings):")
        print("  print(f'My name is {name} and I am {age} years old')")
        print("  print(f'{name} will be {age + 1} next year')")
        print()
        print("4. String format() method:")
        print("  print('Name: {}, Age: {}'.format(name, age))")
        print("  print('Name: {0}, Age: {1}'.format(name, age))")
        print()
        print("5. % Formatting (older style):")
        print("  print('Name: %s, Age: %d' % (name, age))")

    def show_python_global_local(self):
        """Displays Python global vs local scope"""
        print("\n" + "=" * 70)
        print(">> PYTHON GLOBAL VS LOCAL SCOPE")
        print("=" * 70)
        print()
        print("Variables have different scopes based on where they're defined:")
        print()
        print("1. Local Variables:")
        print("  def my_function():")
        print("      x = 10  # Local variable")
        print("      print(x)")
        print()
        print("2. Global Variables:")
        print("  x = 10      # Global variable")
        print("  ")
        print("  def my_function():")
        print("      print(x)  # Accessing global variable")
        print()
        print("3. global Keyword:")
        print("  x = 10")
        print("  ")
        print("  def modify_global():")
        print("      global x")
        print("      x = 20  # Modifying global variable")
        print()
        print("Scope Rules - Python LEGB Rule:")
        print("* L - Local (inside function)")
        print("* E - Enclosing function scope")
        print("* G - Global (module level)")
        print("* B - Built-in names")

    def show_python_identifiers(self):
        """Displays Python identifiers and naming conventions"""
        print("\n" + "=" * 70)
        print(">> PYTHON IDENTIFIERS & NAMING CONVENTIONS")
        print("=" * 70)
        print()
        print("Identifiers are names used to identify variables, functions, classes:")
        print()
        print("Rules for Identifiers:")
        print("* Must start with letter (a-z, A-Z) or underscore (_)")
        print("* Can contain letters, digits (0-9), and underscores")
        print("* Case-sensitive (age and Age are different)")
        print("* Cannot use Python keywords")
        print()
        print("Valid Identifiers:")
        print("  my_var, _private, userName, age2, MAX_SIZE")
        print()
        print("Invalid Identifiers:")
        print("  2name (starts with digit)")
        print("  my-var (contains hyphen)")
        print("  class (Python keyword)")
        print()
        print("Naming Conventions (PEP 8):")
        print("* Variables/functions: snake_case")
        print("  first_name, calculate_area()")
        print("* Classes: PascalCase")
        print("  Student, BankAccount")
        print("* Constants: UPPER_CASE")
        print("  PI, MAX_SIZE, DEFAULT_COLOR")
        print("* Private attributes: _leading_underscore")
        print("  _private_var, _internal_method")

    def show_python_constants(self):
        """Displays Python constants and immutability"""
        print("\n" + "=" * 70)
        print(">> PYTHON CONSTANTS & IMMUTABILITY")
        print("=" * 70)
        print()
        print("Python doesn't have built-in constants, but uses conventions:")
        print()
        print("1. Constant Naming Convention:")
        print("  PI = 3.14159")
        print("  MAX_SIZE = 100")
        print("  DEFAULT_COLOR = 'blue'")
        print("  DATABASE_URL = 'localhost:5432'")
        print()
        print("2. Built-in Constants:")
        print("  True, False    # Boolean constants")
        print("  None           # Null constant")
        print("  __debug__      # Debug mode flag")
        print()
        print("3. Immutable Types (act like constants):")
        print("  numbers = (1, 2, 3)      # Tuple (immutable)")
        print("  text = 'Hello'           # String (immutable)")
        print("  frozen = frozenset([1,2]) # Frozen set")
        print()
        print("4. Creating Constants Module:")
        print("  # constants.py")
        print("  PI = 3.14159")
        print("  GRAVITY = 9.81")
        print("  ")
        print("  # main.py")
        print("  import constants")
        print("  print(constants.PI)")

    def show_python_data_types(self):
        """Displays Python data types overview"""
        print("\n" + "=" * 70)
        print(">> PYTHON DATA TYPES OVERVIEW")
        print("=" * 70)
        print()
        print("Python has several built-in data types:")
        print()
        print("1. Numeric Types:")
        print("  int      - Integers: 42, -17, 0")
        print("  float    - Decimals: 3.14, -2.5, 0.0")
        print("  complex  - Complex numbers: 3+4j, 1-2j")
        print()
        print("2. Text Type:")
        print("  str      - Strings: 'Hello', \"World\", '''Multi-line'''")
        print()
        print("3. Boolean Type:")
        print("  bool     - True or False")
        print()
        print("4. Sequence Types:")
        print("  list     - Mutable: [1, 2, 3]")
        print("  tuple    - Immutable: (1, 2, 3)")
        print("  range    - Number sequences: range(10)")
        print()
        print("5. Mapping Type:")
        print("  dict     - Key-value pairs: {'a': 1, 'b': 2}")
        print()
        print("6. Set Types:")
        print("  set      - Mutable unique items: {1, 2, 3}")
        print("  frozenset- Immutable unique items")
        print()
        print("7. Binary Types:")
        print("  bytes, bytearray, memoryview")
        print()
        print("Check type with type() function:")
        print("  type(42)        # <class 'int'>")
        print("  type('hello')   # <class 'str'>")

    def show_python_number_types(self):
        """Displays Python number types (int, float, complex)"""
        print("\n" + "=" * 70)
        print(">> PYTHON NUMBER TYPES")
        print("=" * 70)
        print()
        print("Python has three numeric types:")
        print()
        print("1. Integer (int):")
        print("  x = 42")
        print("  y = -17")
        print("  z = 0")
        print("  big = 123456789012345678901234567890  # No size limit!")
        print()
        print("  # Different bases:")
        print("  binary = 0b1010      # Binary (10 in decimal)")
        print("  octal = 0o12         # Octal (10 in decimal)")
        print("  hexadecimal = 0xa    # Hexadecimal (10 in decimal)")
        print()
        print("2. Float (floating-point):")
        print("  pi = 3.14159")
        print("  negative = -2.5")
        print("  scientific = 1.2e3   # 1200.0 (scientific notation)")
        print("  small = 1.2e-3      # 0.0012")
        print()
        print("3. Complex:")
        print("  c1 = 3 + 4j")
        print("  c2 = complex(3, 4)  # Same as above")
        print("  print(c1.real)      # 3.0 (real part)")
        print("  print(c1.imag)      # 4.0 (imaginary part)")
        print()
        print("Number Operations:")
        print("  abs(-5)             # 5 (absolute value)")
        print("  round(3.14159, 2)   # 3.14 (round to 2 decimals)")
        print("  pow(2, 3)           # 8 (2^3)")
        print("  divmod(17, 5)       # (3, 2) - quotient and remainder")

    def show_python_type_casting(self):
        """Displays Python type casting and conversion"""
        print("\n" + "=" * 70)
        print(">> PYTHON TYPE CASTING & CONVERSION")
        print("=" * 70)
        print()
        print("Type casting converts one data type to another:")
        print()
        print("1. To Integer - int():")
        print("  int('42')           # 42 (string to int)")
        print("  int(3.7)            # 3 (float to int - truncates)")
        print("  int(True)           # 1 (bool to int)")
        print("  int('0b1010', 2)    # 10 (binary string to int)")
        print()
        print("2. To Float - float():")
        print("  float('3.14')       # 3.14 (string to float)")
        print("  float(42)           # 42.0 (int to float)")
        print("  float('inf')        # inf (infinity)")
        print()
        print("3. To String - str():")
        print("  str(42)             # '42' (int to string)")
        print("  str(3.14)           # '3.14' (float to string)")
        print("  str([1, 2, 3])      # '[1, 2, 3]' (list to string)")
        print()
        print("4. To Boolean - bool():")
        print("  bool(1)             # True")
        print("  bool(0)             # False")
        print("  bool('')            # False (empty string)")
        print("  bool('hello')       # True (non-empty string)")
        print()
        print("5. Collection Conversions:")
        print("  list('abc')         # ['a', 'b', 'c']")
        print("  tuple([1, 2, 3])    # (1, 2, 3)")
        print("  set([1, 1, 2, 2])   # {1, 2}")
        print()
        print("Note: Invalid conversions raise ValueError:")
        print("  int('hello')        # ValueError")