"""
Python Classes and OOP - Object-Oriented Programming in Python
"""


class PythonClassesAndOOP:
    def __init__(self):
        pass

    def show_oop_principles(self):
        """Shows Python Object-Oriented Programming overview"""
        print("\n" + "=" * 75)
        print(">> PYTHON OBJECT-ORIENTED PROGRAMMING")
        print("=" * 75)
        print()
        print("OOP is a programming paradigm based on objects and classes.")
        print()
        print("1. OOP PRINCIPLES:")
        print("+-------------------------------------------+")
        print("| 1. Encapsulation - Data hiding          |")
        print("| 2. Inheritance - Code reusability       |")
        print("| 3. Polymorphism - Multiple forms        |")
        print("| 4. Abstraction - Simplified interface   |")
        print("+-------------------------------------------+")
        print()
        print("2. CLASSES AND OBJECTS:")
        print("+-------------------------------------------+")
        print("| # Class definition                      |")
        print("| class Car:                              |")
        print("|     def __init__(self, brand, model):   |")
        print("|         self.brand = brand              |")
        print("|         self.model = model              |")
        print("|                                         |")
        print("| # Object creation                       |")
        print("| my_car = Car('Toyota', 'Camry')         |")
        print("| print(my_car.brand)  # 'Toyota'        |")
        print("+-------------------------------------------+")
        print()
        print("3. METHODS AND ATTRIBUTES:")
        print("+-------------------------------------------+")
        print("| class Person:                           |")
        print("|     species = 'Homo sapiens'  # Class attribute |")
        print("|                                         |")
        print("|     def __init__(self, name, age):      |")
        print("|         self.name = name  # Instance attribute |")
        print("|         self.age = age                  |")
        print("|                                         |")
        print("|     def greet(self):  # Instance method |")
        print("|         return f'Hi, I am {self.name}'  |")
        print("|                                         |")
        print("| person = Person('Alice', 30)            |")
        print("| print(person.greet())  # 'Hi, I am Alice' |")
        print("+-------------------------------------------+")

    def show_python_classes(self):
        """Shows Python classes and objects with creation and usage examples"""
        print("\n" + "=" * 75)
        print(">> CLASSES AND OBJECTS")
        print("=" * 75)
        print()
        print("Classes are blueprints for creating objects.")
        print()
        print("1. DEFINING A CLASS:")
        print("+-------------------------------------------+")
        print("| class Student:                          |")
        print("|     # Class variable (shared by all)    |")
        print("|     school_name = 'Python High School'  |")
        print("|                                         |")
        print("|     # Constructor method                |")
        print("|     def __init__(self, name, grade):    |")
        print("|         # Instance variables (unique)    |")
        print("|         self.name = name                |")
        print("|         self.grade = grade              |")
        print("|         self.courses = []               |")
        print("+-------------------------------------------+")
        print()
        print("2. CREATING AND USING OBJECTS:")
        print("+-------------------------------------------+")
        print("| # Creating objects (instances)          |")
        print("| student1 = Student('Alice', 'A')        |")
        print("| student2 = Student('Bob', 'B')          |")
        print("|                                         |")
        print("| # Accessing attributes                  |")
        print("| print(student1.name)        # 'Alice'  |")
        print("| print(student1.school_name) # 'Python High School' |")
        print("|                                         |")
        print("| # Modifying attributes                  |")
        print("| student1.grade = 'A+'                  |")
        print("| student1.courses.append('Math')        |")
        print("+-------------------------------------------+")
        print()
        print("3. INSTANCE vs CLASS ATTRIBUTES:")
        print("+-------------------------------------------+")
        print("| # Each object has its own instance attributes |")
        print("| print(student1.name)  # 'Alice'        |")
        print("| print(student2.name)  # 'Bob'          |")
        print("|                                         |")
        print("| # All objects share class attributes    |")
        print("| Student.school_name = 'New School'     |")
        print("| print(student1.school_name) # 'New School' |")
        print("| print(student2.school_name) # 'New School' |")
        print("|                                         |")
        print("| # Check object type                     |")
        print("| print(type(student1))  # <class '__main__.Student'> |")
        print("| print(isinstance(student1, Student)) # True |")
        print("+-------------------------------------------+")

    def show_python_self(self):
        """Shows the self parameter and its role in Python classes"""
        print("\n" + "=" * 75)
        print(">> SELF PARAMETER")
        print("=" * 75)
        print()
        print("Self parameter refers to the instance of the class.")
        print()
        print("1. UNDERSTANDING SELF:")
        print("+-------------------------------------------+")
        print("| class Circle:                           |")
        print("|     def __init__(self, radius):         |")
        print("|         # self refers to the specific   |")
        print("|         # instance being created        |")
        print("|         self.radius = radius           |")
        print("|                                         |")
        print("|     def get_area(self):                 |")
        print("|         # self accesses instance data   |")
        print("|         return 3.14159 * self.radius ** 2 |")
        print("|                                         |")
        print("| # When calling methods, Python          |")
        print("| # automatically passes self            |")
        print("| circle = Circle(5)                      |")
        print("| area = circle.get_area()  # area = 78.54 |")
        print("+-------------------------------------------+")
        print()
        print("2. SELF IN DIFFERENT METHODS:")
        print("+-------------------------------------------+")
        print("| class BankAccount:                      |")
        print("|     def __init__(self, owner, balance=0): |")
        print("|         self.owner = owner              |")
        print("|         self.balance = balance          |")
        print("|                                         |")
        print("|     def deposit(self, amount):          |")
        print("|         self.balance += amount          |")
        print("|         return self.balance             |")
        print("|                                         |")
        print("|     def withdraw(self, amount):         |")
        print("|         if amount <= self.balance:      |")
        print("|             self.balance -= amount      |")
        print("|         return self.balance             |")
        print("|                                         |")
        print("|     def get_info(self):                 |")
        print("|         return f'{self.owner}: ${self.balance}' |")
        print("+-------------------------------------------+")
        print()
        print("3. SELF vs OTHER NAMES:")
        print("+-------------------------------------------+")
        print("| # 'self' is just a convention          |")
        print("| # You could use any name, but don't!    |")
        print("| class Example:                          |")
        print("|     def __init__(this, value):  # Works but bad |")
        print("|         this.value = value              |")
        print("|                                         |")
        print("| # Always use 'self' - it's the standard |")
        print("| # and expected by other Python developers |")
        print("|                                         |")
        print("| # Multiple instances have different self |")
        print("| account1 = BankAccount('Alice', 100)    |")
        print("| account2 = BankAccount('Bob', 200)      |")
        print("| # Each method call uses their own 'self' |")
        print("+-------------------------------------------+")

    def show_python_methods(self):
        """Shows different types of methods in Python classes"""
        print("\n" + "=" * 75)
        print(">> PYTHON METHODS")
        print("=" * 75)
        print()
        print("Methods are functions defined inside a class.")
        print()
        print("1. INSTANCE METHODS:")
        print("+-------------------------------------------+")
        print("| class Calculator:                       |")
        print("|     def __init__(self, name):           |")
        print("|         self.name = name                |")
        print("|         self.result = 0                 |")
        print("|                                         |")
        print("|     # Instance methods work with 'self' |")
        print("|     def add(self, x, y):                |")
        print("|         self.result = x + y             |")
        print("|         return self.result              |")
        print("|                                         |")
        print("|     def multiply(self, x, y):           |")
        print("|         self.result = x * y             |")
        print("|         return self.result              |")
        print("|                                         |")
        print("| calc = Calculator('MyCalc')             |")
        print("| print(calc.add(5, 3))      # 8         |")
        print("+-------------------------------------------+")
        print()
        print("2. CLASS METHODS:")
        print("+-------------------------------------------+")
        print("| class Person:                           |")
        print("|     population = 0                      |")
        print("|                                         |")
        print("|     def __init__(self, name):           |")
        print("|         self.name = name                |")
        print("|         Person.population += 1          |")
        print("|                                         |")
        print("|     @classmethod                        |")
        print("|     def get_population(cls):            |")
        print("|         return cls.population           |")
        print("|                                         |")
        print("|     @classmethod                        |")
        print("|     def create_anonymous(cls):          |")
        print("|         return cls('Anonymous')         |")
        print("|                                         |")
        print("| # Call class methods on class or instance |")
        print("| print(Person.get_population())  # 0    |")
        print("| person1 = Person('Alice')               |")
        print("| print(Person.get_population())  # 1    |")
        print("+-------------------------------------------+")
        print()
        print("3. STATIC METHODS:")
        print("+-------------------------------------------+")
        print("| class MathUtils:                        |")
        print("|     # Static methods don't need self or cls |")
        print("|     @staticmethod                       |")
        print("|     def add_numbers(x, y):              |")
        print("|         return x + y                    |")
        print("|                                         |")
        print("|     @staticmethod                       |")
        print("|     def is_even(number):                |")
        print("|         return number % 2 == 0          |")
        print("|                                         |")
        print("| # Call static methods without creating instance |")
        print("| print(MathUtils.add_numbers(5, 3))  # 8 |")
        print("| print(MathUtils.is_even(4))         # True |")
        print("|                                         |")
        print("| # Can also call on instances            |")
        print("| utils = MathUtils()                     |")
        print("| print(utils.add_numbers(2, 3))     # 5 |")
        print("+-------------------------------------------+")

    def show_python_properties(self):
        """Shows Python properties for getter/setter access control"""
        print("\n" + "=" * 75)
        print(">> PYTHON PROPERTIES")
        print("=" * 75)
        print()
        print("Properties provide getter/setter access control.")
        print()
        print("1. USING @property DECORATOR:")
        print("+-------------------------------------------+")
        print("| class Temperature:                      |")
        print("|     def __init__(self, celsius=0):      |")
        print("|         self._celsius = celsius         |")
        print("|                                         |")
        print("|     @property                           |")
        print("|     def celsius(self):                  |")
        print("|         return self._celsius            |")
        print("|                                         |")
        print("|     @celsius.setter                     |")
        print("|     def celsius(self, value):           |")
        print("|         if value < -273.15:             |")
        print("|             raise ValueError('Below absolute zero') |")
        print("|         self._celsius = value           |")
        print("|                                         |")
        print("|     @property                           |")
        print("|     def fahrenheit(self):               |")
        print("|         return (self._celsius * 9/5) + 32 |")
        print("+-------------------------------------------+")
        print()
        print("2. READ-ONLY PROPERTIES:")
        print("+-------------------------------------------+")
        print("| class Circle:                           |")
        print("|     def __init__(self, radius):         |")
        print("|         self._radius = radius           |")
        print("|                                         |")
        print("|     @property                           |")
        print("|     def radius(self):                   |")
        print("|         return self._radius             |")
        print("|                                         |")
        print("|     @property                           |")
        print("|     def area(self):  # Read-only        |")
        print("|         return 3.14159 * self._radius ** 2 |")
        print("|                                         |")
        print("|     @property                           |")
        print("|     def diameter(self):  # Read-only    |")
        print("|         return 2 * self._radius         |")
        print("|                                         |")
        print("| circle = Circle(5)                      |")
        print("| print(circle.area)      # 78.54        |")
        print("| # circle.area = 100  # Error! Read-only |")
        print("+-------------------------------------------+")
        print()
        print("3. PROPERTY WITH VALIDATION:")
        print("+-------------------------------------------+")
        print("| class Person:                           |")
        print("|     def __init__(self, name, age):      |")
        print("|         self._name = name               |")
        print("|         self._age = age                 |")
        print("|                                         |")
        print("|     @property                           |")
        print("|     def age(self):                      |")
        print("|         return self._age                |")
        print("|                                         |")
        print("|     @age.setter                         |")
        print("|     def age(self, value):               |")
        print("|         if not isinstance(value, int):   |")
        print("|             raise TypeError('Age must be integer') |")
        print("|         if value < 0 or value > 150:    |")
        print("|             raise ValueError('Invalid age') |")
        print("|         self._age = value               |")
        print("+-------------------------------------------+")

    def show_python_inheritance(self):
        """Shows Python inheritance and method overriding"""
        print("\n" + "=" * 75)
        print(">> PYTHON INHERITANCE")
        print("=" * 75)
        print()
        print("Inheritance allows classes to inherit from other classes.")
        print()
        print("1. BASIC INHERITANCE:")
        print("+-------------------------------------------+")
        print("| # Parent class (Base class)             |")
        print("| class Animal:                           |")
        print("|     def __init__(self, name, species):  |")
        print("|         self.name = name                |")
        print("|         self.species = species          |")
        print("|                                         |")
        print("|     def make_sound(self):               |")
        print("|         return 'Some generic sound'     |")
        print("|                                         |")
        print("|     def info(self):                     |")
        print("|         return f'{self.name} is a {self.species}' |")
        print("|                                         |")
        print("| # Child class (Derived class)           |")
        print("| class Dog(Animal):                      |")
        print("|     def __init__(self, name, breed):    |")
        print("|         super().__init__(name, 'Dog')   |")
        print("|         self.breed = breed              |")
        print("|                                         |")
        print("|     def make_sound(self):  # Override   |")
        print("|         return 'Woof!'                  |")
        print("+-------------------------------------------+")
        print()
        print("2. METHOD OVERRIDING:")
        print("+-------------------------------------------+")
        print("| class Cat(Animal):                      |")
        print("|     def __init__(self, name, indoor=True): |")
        print("|         super().__init__(name, 'Cat')   |")
        print("|         self.indoor = indoor            |")
        print("|                                         |")
        print("|     def make_sound(self):               |")
        print("|         return 'Meow!'                  |")
        print("|                                         |")
        print("|     def info(self):  # Override and extend |")
        print("|         base_info = super().info()      |")
        print("|         location = 'indoor' if self.indoor else 'outdoor' |")
        print("|         return f'{base_info} ({location})' |")
        print("|                                         |")
        print("| # Using inherited classes               |")
        print("| dog = Dog('Buddy', 'Golden Retriever')  |")
        print("| cat = Cat('Whiskers', True)             |")
        print("| print(dog.make_sound())  # 'Woof!'     |")
        print("| print(cat.info())  # 'Whiskers is a Cat (indoor)' |")
        print("+-------------------------------------------+")
        print()
        print("3. MULTIPLE INHERITANCE:")
        print("+-------------------------------------------+")
        print("| class Flyable:                          |")
        print("|     def fly(self):                      |")
        print("|         return 'Flying through the air' |")
        print("|                                         |")
        print("| class Swimmable:                        |")
        print("|     def swim(self):                     |")
        print("|         return 'Swimming in water'      |")
        print("|                                         |")
        print("| # Multiple inheritance                  |")
        print("| class Duck(Animal, Flyable, Swimmable): |")
        print("|     def __init__(self, name):           |")
        print("|         Animal.__init__(self, name, 'Duck') |")
        print("|                                         |")
        print("|     def make_sound(self):               |")
        print("|         return 'Quack!'                 |")
        print("|                                         |")
        print("| duck = Duck('Donald')                   |")
        print("| print(duck.fly())    # 'Flying through the air' |")
        print("| print(duck.swim())   # 'Swimming in water' |")
        print("+-------------------------------------------+")

    def show_python_polymorphism(self):
        """Shows Python polymorphism and duck typing"""
        print("\n" + "=" * 75)
        print(">> PYTHON POLYMORPHISM")
        print("=" * 75)
        print()
        print("Polymorphism allows objects of different types to be treated uniformly.")
        print()
        print("1. METHOD OVERRIDING POLYMORPHISM:")
        print("+-------------------------------------------+")
        print("| class Shape:                            |")
        print("|     def area(self):                     |")
        print("|         raise NotImplementedError('Subclass must implement') |")
        print("|                                         |")
        print("|     def perimeter(self):                |")
        print("|         raise NotImplementedError('Subclass must implement') |")
        print("|                                         |")
        print("| class Rectangle(Shape):                 |")
        print("|     def __init__(self, width, height):  |")
        print("|         self.width = width              |")
        print("|         self.height = height            |")
        print("|                                         |")
        print("|     def area(self):                     |")
        print("|         return self.width * self.height |")
        print("|                                         |")
        print("|     def perimeter(self):                |")
        print("|         return 2 * (self.width + self.height) |")
        print("+-------------------------------------------+")
        print()
        print("2. POLYMORPHIC BEHAVIOR:")
        print("+-------------------------------------------+")
        print("| class Circle(Shape):                    |")
        print("|     def __init__(self, radius):         |")
        print("|         self.radius = radius            |")
        print("|                                         |")
        print("|     def area(self):                     |")
        print("|         return 3.14159 * self.radius ** 2 |")
        print("|                                         |")
        print("|     def perimeter(self):                |")
        print("|         return 2 * 3.14159 * self.radius |")
        print("|                                         |")
        print("| # Polymorphic function                  |")
        print("| def describe_shape(shape):              |")
        print("|     print(f'Area: {shape.area():.2f}')  |")
        print("|     print(f'Perimeter: {shape.perimeter():.2f}') |")
        print("|                                         |")
        print("| # Same function works with different shapes |")
        print("| rectangle = Rectangle(5, 3)             |")
        print("| circle = Circle(4)                      |")
        print("| describe_shape(rectangle)  # Uses Rectangle methods |")
        print("| describe_shape(circle)     # Uses Circle methods |")
        print("+-------------------------------------------+")
        print()
        print("3. DUCK TYPING:")
        print("+-------------------------------------------+")
        print("| # If it walks like a duck and quacks    |")
        print("| # like a duck, then it is a duck        |")
        print("|                                         |")
        print("| class FileWriter:                       |")
        print("|     def write(self, text):              |")
        print("|         with open('file.txt', 'w') as f: |")
        print("|             f.write(text)               |")
        print("|                                         |")
        print("| class ConsoleWriter:                    |")
        print("|     def write(self, text):              |")
        print("|         print(text)                     |")
        print("|                                         |")
        print("| # Function works with any object that   |")
        print("| # has a 'write' method                  |")
        print("| def save_data(writer, data):            |")
        print("|     writer.write(data)                  |")
        print("|                                         |")
        print("| save_data(FileWriter(), 'Hello File')   |")
        print("| save_data(ConsoleWriter(), 'Hello Console') |")
        print("+-------------------------------------------+")

    def show_python_encapsulation(self):
        """Shows Python encapsulation and access control"""
        print("\n" + "=" * 75)
        print(">> PYTHON ENCAPSULATION")
        print("=" * 75)
        print()
        print("Encapsulation hides internal implementation details.")
        print()
        print("1. PRIVATE ATTRIBUTES:")
        print("+-------------------------------------------+")
        print("| class BankAccount:                      |")
        print("|     def __init__(self, initial_balance): |")
        print("|         # Public attribute              |")
        print("|         self.account_holder = 'User'    |")
        print("|                                         |")
        print("|         # Protected attribute (convention) |")
        print("|         self._account_number = 'ACC123'  |")
        print("|                                         |")
        print("|         # Private attribute (name mangling) |")
        print("|         self.__balance = initial_balance |")
        print("|                                         |")
        print("|     def get_balance(self):  # Public method |")
        print("|         return self.__balance           |")
        print("|                                         |")
        print("|     def deposit(self, amount):          |")
        print("|         if self.__validate_amount(amount): |")
        print("|             self.__balance += amount    |")
        print("|                                         |")
        print("|     def __validate_amount(self, amount): # Private method |")
        print("|         return amount > 0               |")
        print("+-------------------------------------------+")
        print()
        print("2. ACCESS CONTROL:")
        print("+-------------------------------------------+")
        print("| account = BankAccount(1000)             |")
        print("|                                         |")
        print("| # Public access - works                 |")
        print("| print(account.account_holder)  # 'User' |")
        print("|                                         |")
        print("| # Protected access - works but discouraged |")
        print("| print(account._account_number)  # 'ACC123' |")
        print("|                                         |")
        print("| # Private access - AttributeError       |")
        print("| # print(account.__balance)  # Error!    |")
        print("|                                         |")
        print("| # Access through name mangling (not recommended) |")
        print("| print(account._BankAccount__balance)  # 1000 |")
        print("|                                         |")
        print("| # Proper access through public methods  |")
        print("| print(account.get_balance())  # 1000    |")
        print("+-------------------------------------------+")
        print()
        print("3. GETTERS AND SETTERS:")
        print("+-------------------------------------------+")
        print("| class Student:                          |")
        print("|     def __init__(self, name):           |")
        print("|         self.__name = name              |")
        print("|         self.__grades = []              |")
        print("|                                         |")
        print("|     # Getter methods                    |")
        print("|     def get_name(self):                 |")
        print("|         return self.__name              |")
        print("|                                         |")
        print("|     def get_grades(self):               |")
        print("|         return self.__grades.copy()  # Return copy |")
        print("|                                         |")
        print("|     # Setter methods with validation    |")
        print("|     def add_grade(self, grade):         |")
        print("|         if 0 <= grade <= 100:           |")
        print("|             self.__grades.append(grade) |")
        print("|         else:                           |")
        print("|             raise ValueError('Invalid grade') |")
        print("|                                         |")
        print("|     def get_average(self):              |")
        print("|         if self.__grades:               |")
        print("|             return sum(self.__grades) / len(self.__grades) |")
        print("|         return 0                        |")
        print("+-------------------------------------------+")

    def show_python_nested_classes(self):
        """Shows Python inner classes and their usage"""
        print("\n" + "=" * 75)
        print(">> INNER CLASSES")
        print("=" * 75)
        print()
        print("Inner classes are classes defined inside other classes.")
        print()
        print("1. BASIC INNER CLASS:")
        print("+-------------------------------------------+")
        print("| class Computer:                         |")
        print("|     def __init__(self, brand):          |")
        print("|         self.brand = brand              |")
        print("|         self.cpu = self.CPU()           |")
        print("|         self.gpu = self.GPU()           |")
        print("|                                         |")
        print("|     class CPU:  # Inner class           |")
        print("|         def __init__(self):             |")
        print("|             self.cores = 4              |")
        print("|             self.speed = '3.2 GHz'      |")
        print("|                                         |")
        print("|         def process(self):              |")
        print("|             return 'Processing data...' |")
        print("|                                         |")
        print("|     class GPU:  # Another inner class   |")
        print("|         def __init__(self):             |")
        print("|             self.memory = '8GB'         |")
        print("|                                         |")
        print("|         def render(self):               |")
        print("|             return 'Rendering graphics...' |")
        print("+-------------------------------------------+")
        print()
        print("2. ACCESSING INNER CLASSES:")
        print("+-------------------------------------------+")
        print("| # Create outer class instance           |")
        print("| my_computer = Computer('Dell')          |")
        print("|                                         |")
        print("| # Access inner class through outer instance |")
        print("| print(my_computer.cpu.cores)    # 4    |")
        print("| print(my_computer.cpu.process()) # 'Processing data...' |")
        print("| print(my_computer.gpu.render())  # 'Rendering graphics...' |")
        print("|                                         |")
        print("| # Create inner class directly           |")
        print("| standalone_cpu = Computer.CPU()         |")
        print("| print(standalone_cpu.process())         |")
        print("+-------------------------------------------+")
        print()
        print("3. INNER CLASS WITH OUTER REFERENCE:")
        print("+-------------------------------------------+")
        print("| class University:                       |")
        print("|     def __init__(self, name):           |")
        print("|         self.name = name                |")
        print("|         self.students = []              |")
        print("|                                         |")
        print("|     def enroll_student(self, student_name): |")
        print("|         student = self.Student(student_name, self) |")
        print("|         self.students.append(student)   |")
        print("|         return student                  |")
        print("|                                         |")
        print("|     class Student:                      |")
        print("|         def __init__(self, name, university): |")
        print("|             self.name = name            |")
        print("|             self.university = university # Reference to outer |")
        print("|             self.courses = []           |")
        print("|                                         |")
        print("|         def get_university_info(self):  |")
        print("|             return f'Student at {self.university.name}' |")
        print("|                                         |")
        print("| uni = University('MIT')                 |")
        print("| student = uni.enroll_student('Alice')   |")
        print("| print(student.get_university_info())  # 'Student at MIT' |")
        print("+-------------------------------------------+")